### ISSUE TITLE
Meny: Cell\Remove All Output fails

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1271] opened 2020-05-11 09:25 UTC
Creates this message and terminates wxMaxima:
![image](https://user-images.githubusercontent.com/2638713/81545980-ffca5f00-9379-11ea-88bd-699169faad33.png)

(%i1)	build_info();
(%o1)	build_info(version="branch_5_43_base_509_g1cd666c87",timestamp="2020-05-11 00:05:51",
host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.0.0",maxima_userdir=
"C:/Users/xxx/maxima",maxima_tempdir="C:/Users/xxx/AppData/Local/Temp",maxima_objdir
="C:/Users/xxxx/maxima/binary/branch_5_43_base_509_g1cd666c87/sbcl/2_0_0",maxima_frontend
="wxMaxima",maxima_frontend_version="20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by gunterkoenigsmann** [comment] 2020-05-11 15:20
Hmmm... ...this error I cannot reproduce on my computer => there seems to be an important difference between your test setup and mine.

Does the problem only arise in specific worksheets? If I can make wxMaxima crash on my computer normally gdb gives me a backtrace that tells me exactly which line of program code the problem relies in - which makes resolving it easy.

**Comment by ReneSci** [comment] 2020-05-12 07:34
Yes, is seem only to be a problem with my large worksheet. By pressing the "continue" bottom each time this message pups up ( about 19 times in my case ) it works ok and removes all output cells.

With smaller work sheets there is no problem.

Reverting back to this nightly build (below) the bug was not present:
(%i1)	build_info();
(%o1)	build_info(version="branch_5_43_base_473_g0c3b407a1",timestamp="2020-04-21 00:03:39",host=
"x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.0.0",maxima_userdir="C:/Users/xxx/maxima",
maxima_tempdir="C:/Users/xx/AppData/Local/Temp",maxima_objdir=
"C:/Users/xxxx/maxima/binary/branch_5_43_base_473_g0c3b407a1/sbcl/2_0_0",maxima_frontend="wxMaxima",
maxima_frontend_version="20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by ReneSci** [comment] 2020-06-02 09:24
This bug is still present (working with a large worksheet)
![image](https://user-images.githubusercontent.com/2638713/83503516-75ca6d80-a4c3-11ea-928c-2561ac1b247b.png)

(%o1)	build_info(version="branch_5_43_base_517_gb55b72413",timestamp=
"2020-06-02 00:04:37",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.0.0"
,maxima_userdir="C:/Users/xxx/maxima",maxima_tempdir=
"C:/Users/xxx/AppData/Local/Temp",maxima_objdir=
"C:/Users/xxx/maxima/binary/branch_5_43_base_517_gb55b72413/sbcl/2_0_0",
maxima_frontend="wxMaxima",maxima_frontend_version=
"20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

**Comment by KubaO** [comment] 2020-06-04 06:37
You'll have to provide an example of a file. Try and remove sections from it to shrink it, or replace text by [lorem ipsum](https://www.lipsum.com/) to obfuscate it.

**Closed** 2020-06-04 06:38 UTC
Labels: bug, no-repro

**Comment by gunterkoenigsmann** [comment] 2020-06-04 07:33
I have finally found a way to crash wxMaxima when removing output: If a cell-in-a-cell-in-a-cell (a parenthesis inside a fraction inside a square root inside a function inside another function...) is nested several thousand levels deep removing all output involves a several-thousand-level-deep recursice function call and runs out of stack space. @ReneSci : Could this be the problem?
If it is I have no idea on how to resolve this problem, though...
