### ISSUE TITLE
High cpu usage on FreeBSD

### ISSUE THREAD

**Issue by ghost** [wxMaxima-developers/wxmaxima#1290] opened 2020-05-27 23:31 UTC
It has been noticed that wxMaxima can take up to 100% of cpu on FreeBSD.
I have not managed to find the cause of the issue yet, but I get lots of errors like the following that might be related:
```
(wxmaxima:51809): Gtk-WARNING **: 23:59:04.953: gtk_widget_size_allocate(): attempt to underallocate wxPizza's child GtkButton 0x804f166c0. Allocation is 70x28, but minimum required size is 94x34.

(wxmaxima:51809): Gtk-WARNING **: 23:59:04.953: gtk_widget_size_allocate(): attempt to underallocate wxPizza's child GtkButton 0x804f16880. Allocation is 70x28, but minimum required size is 110x34.

(wxmaxima:51809): Gtk-WARNING **: 23:59:04.953: gtk_widget_size_allocate(): attempt to underallocate wxPizza's child GtkButton 0x804f16a40. Allocation is 70x28, but minimum required size is 106x34.
```

Bug report on bugs.freebsd.org:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246599

**Comment by gunterkoenigsmann** [comment] 2020-05-31 16:35
I've just seen that my last try to post a comment to this bug report has failed.

When does the high CPU usage happen? If it is only within the first minute of the program being run I believe that the next version will contain a remedy. Else if we find out how to trigger that perhaps there is a way to improve things.

Kind regards,

         Gunter.

**Comment by lsalvadore** [comment] 2020-05-31 22:06
The high cpu usage starts with wxmaxima and does not end until wxmaxima quits.
I am still looking into the issue and I will add any new element I manage to find.

Thanks.

**Comment by KubaO** [comment] 2020-05-31 23:32
It looks as if some background thread got stuck maybe. Really interesting.

**Comment by gunterkoenigsmann** [comment] 2020-06-01 00:08
Interesting idea. In that case pressing Ctrl+R would cause wxMaxima to hang indefinitely as killing the Maxima process always waits for all background threads to exit.

Another way to get 100% CPU without the program hanging would be if each call wxMaxima::OnIdle caused another call to wxMaxima::OnIdle - either because event.RequestMore() is called or because of a bug in wxWidgets.

**Comment by gunterkoenigsmann** [comment] 2020-06-01 04:33
What I am afreid of (since Ii this case I would not know a good option) is that

      wxMaxima::TryToReadDataFromMaxima()

on FreeBSD perhaps could trigger an idle event: On MS Windows we sometimes aren't informed that data from Maxima has arrived. But we get an idle event if data arrives so we trigger reading more data on idle events. This allows us also not to read all data in one go if there is megabytes of data and we want to keep the GUI responsive while reading - which isn't bad on other OSes, neither.

**Comment by lsalvadore** [comment] 2020-06-01 19:01
I will try that commit and tell you if it helps.

> Interesting idea. In that case pressing Ctrl+R would cause wxMaxima to hang indefinitely as killing the Maxima process always waits for all background threads to exit.

I tried Ctrl+R but nothing happened: wxMaxima did not hang and nothing was killed. Are you sure this is the right combination? Is it implemented on FreeBSD?

**Comment by lsalvadore** [comment] 2020-06-01 23:16
I tested the commit and the issue is still present unfortunately.

**Comment by KubaO** [comment] 2020-07-07 06:38
It seems that the ghost has left. I'll close this until we get re-confirmation that it still is a problem. Otherwise this issue will just languish open.

**Closed by KubaO** 2020-07-07 06:38 UTC
