### ISSUE TITLE
Find dialog - Mac OS X

### ISSUE THREAD

**Issue by dpgoldenberg** [wxMaxima-developers/wxmaxima#537] opened 2015-08-06 17:23 UTC
This is another little quirk I have noticed.  If the find dialog box is open, cells in worksheets can't be deleted.  This can be a nuisance if one is searching for repeated instances of some text and wants to edit them successively.

Also, it would be nice if the search function could wrap around the end and beginning of a file, so that it didn't matter much if it is searching down or up.

Thanks,
David

**Comment by dpgoldenberg** [comment] 2015-08-06 17:34
I just noticed that the open Find dialog also disables the copy and paste functions.

David

**Comment by gunterkoenigsmann** [comment] 2015-08-06 18:55
Thanks for this bug report.

Unfortunately I have until now never found the reason for this. 
behavior. Don't know if it is a wxWidgets issue.

Kind regards,

   Gunter.

**Comment by KubaO** [comment] 2020-07-10 19:18
Can't reproduce either problem on Windows at the very least. Closing. @dpgoldenberg  Please reopen if this is still a problem in the nightly build or in the master.

**Closed by KubaO** 2020-07-10 19:18 UTC
Labels: bug
