### ISSUE TITLE
printing broken in 18.12.0 and 19.01.0 (in certain kinds of output cells only?)

### ISSUE THREAD

**Issue by yurytch** [wxMaxima-developers/wxmaxima#1079] opened 2019-01-17 08:41 UTC
![20190117_print_preview](https://user-images.githubusercontent.com/8167943/51306266-d246fd00-1a34-11e9-86bf-1e31eebd6eed.jpeg)
The system is 64-bit Slackware. The wxmx (remove the bogus .gz from the 
[20190117_вопросы_ответы.wxmx.gz](https://github.com/wxMaxima-developers/wxmaxima/files/2767748/20190117_._.wxmx.gz)
filename) and screenshot from 19.01.0 are attached. I've tested only with print preview, PS file output and PDF file output.

**Comment by gunterkoenigsmann** [comment] 2019-01-21 05:18
I hope 19.01.1 resolves this issue.

**Comment by yurytch** [comment] 2019-02-05 08:11
Unfortunately, even 19.01.3 is no help. I've upgraded wx to 3.0.4, and re-built wxMaxima, to no avail.
It may happen, actually, that this is sort of a unique bug, with this exact cell expression triggering the faulty behaviour (I can't now produce a correct print output even in older versions). Looking closely at the output, I see the widths of the glyphs w/r to the output lines as such are okay, but the lines' indents are off, and the heights calculated for the wrapping are off too, likely.
If it's of any help, I'll tinker with fonts and scripts in this file, try to locate the offending thing more precisely?

**Comment by yurytch** [comment] 2019-02-05 08:45
Tried changing fonts in the math output, and so far I could get correct output in print preview only with fonts from Cormorant, Gentium, Gentium Plus and Libertinus families.
Asana, Cambria, Arial, Liberation, Charis SIL and CMU do not work.

**Comment by yurytch** [comment] 2019-02-05 08:47
In fact, the fonts settings processing looks peculiar. E.g., I can't set 'Times New Roman'as math output font, it gets auto-substituted immediately to 'Liberation Serif'. And why are the glyphs for greek symbols taken from some other font face?

**Comment by gunterkoenigsmann** [comment] 2019-02-09 21:15
Ok... ...I hope the issue is resolved in 19.02.0 If it isn't please reopen this ticket!

**Closed by gunterkoenigsmann** 2019-02-09 21:15 UTC

**Comment by yurytch** [comment] 2019-02-10 07:14
Thank you for spending your time on that... Unfortunately, the issue's still there.
Sorry to impose on your time again, but I'll reopen as at the moment I rather don't think it's my system. 
Right now I'm seeing 'Print preview' output hashed AND moved to the left of cell left bracket with 'Math font' set to 'CMU Serif' in 15pt
And I see the same output hashed but NOT moved to the left with 'Math font' still set to 'CMU Serif' but in 16pt.
'CMU Serif' in 14 pt -> 
![20190210_print_preview_cmu_serif_14 15 16pt](https://user-images.githubusercontent.com/8167943/52530816-2c796c00-2d1c-11e9-9997-88854212b48c.jpeg)
correct 'print preview' output (!?).
Same file, same cell, only the pointsize of 'math font' changed in settings.
![20190210_print_preview_cmu_serif_14 15 16pt](https://user-images.githubusercontent.com/8167943/52530833-8d08a900-2d1c-11e9-8340-f498410d432b.jpeg)

**Comment by yurytch** [comment] 2019-03-17 05:06
Verifying... Not an issue in 19.03.1. Thank you!
