### ISSUE TITLE
wxmaxima 20.04 crashes when exporting to latex

### ISSUE THREAD

**Issue by jose-matos** [wxMaxima-developers/wxmaxima#1295] opened 2020-06-02 13:43 UTC
I am using wxmaxima in Fedora 32.
When exporting to latex wxmaxima crashes with the following backtrace:

ASSERT INFO:
/usr/include/wx-3.0/wx/strvararg.h(456): assert "(argtype & (wxFormatStringSpecifier<T>::value)) == argtype" failed in wxArgNormalizer(): format specifier doesn't match argument type

BACKTRACE:
[1] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&)
[2] wxEvtHandler::SearchDynamicEventTable(wxEvent&)
[3] wxEvtHandler::TryHereOnly(wxEvent&)
[4] wxEvtHandler::DoTryChain(wxEvent&)
[5] wxEvtHandler::ProcessEvent(wxEvent&)
[6] wxWindowBase::TryAfter(wxEvent&)
[7] wxEvtHandler::SafelyProcessEvent(wxEvent&)
[8] wxMenuBase::SendEvent(int, int)
[9] g_closure_invoke
[10] g_signal_emit_valist
[11] g_signal_emit
[12] gtk_widget_activate
[13] gtk_menu_shell_activate_item
[14] g_signal_emit_valist
[15] g_signal_emit
[16] gtk_main_do_event
[17] g_main_context_dispatch
[18] g_main_loop_run
[19] gtk_main
[20] wxGUIEventLoop::DoRun()
[21] wxEventLoopBase::Run()
[22] wxAppConsoleBase::MainLoop()
[23] GOMP_parallel
[24] __libc_start_main

The previous stable version 20.03.1 does not show this problem.

**Comment by KubaO** [comment] 2020-06-02 14:26
This is fixed in the master and is a duplicate of a closed issue. Thank you for the report.

**Comment by jose-matos** [comment] 2020-06-02 14:29
Thank you. :+1:  :-)

**Comment by KubaO** [comment] 2020-06-02 16:29
This is a duplicate of #1288. Closing.

**Closed by KubaO** 2020-06-02 16:29 UTC
Labels: bug, confirmed, known issue

**Comment by jose-matos** [comment] 2020-06-03 15:41
I apologize for reopening this bug. I use the patch from the bug you mentioned in 20.04 code I can confirm that it works when copying the formula content to the clipboard but it fails when exporting to an external file (File->Export)

**Comment by KubaO** [comment] 2020-06-03 15:54
Oh, I apologize that it wasn’t fixed as I thought :)

**Comment by KubaO** [comment] 2020-06-04 06:32
I can't reproduce this bug, sorry. If you can try with the most recent checkout from master, and provide an example of a failing file, I'll be able to help.

**Comment by jose-matos** [comment] 2020-06-04 09:29
> I can't reproduce this bug, sorry. If you can try with the most recent checkout from master, and provide an example of a failing file, I'll be able to help. I tried with fairly complex files and there are no crashes.

Thank you. I built 20.06.0 and the bug is gone. The updates are already on the testing stage for Fedora 31 and 32. :-)

Thank you for the prompt reply.
