### ISSUE TITLE
Dark Mode on MacOS makes text unreadable

### ISSUE THREAD

**Issue by MrColoratus** [wxMaxima-developers/wxmaxima#1080] opened 2019-01-18 15:50 UTC
Using wxMaxima version 19.01.0 on macOS Mojave (10.14.2), if I turn on Dark mode, the text becomes lighter in color, while the background stays the same. This makes it very difficult to read the UI.

**Dark Mode off**
<img width="878" alt="darkmodeoff" src="https://user-images.githubusercontent.com/17001562/51397018-98631d00-1b40-11e9-959c-77758993703b.png">

**Dark Mode on**
<img width="880" alt="darkmodeon" src="https://user-images.githubusercontent.com/17001562/51397020-98fbb380-1b40-11e9-83c6-69aa8a8fdb4a.png">

**Comment by gunterkoenigsmann** [comment] 2019-01-21 05:17
I always hoped that someone would be able to test if the worksheet works in dark mode.
No idea how it is supposed to look like in dark mode, but at least it seems to be readable.

The colors of the rest of the controls are chosen by wxWidgets => This half of the issue needs to be resolved by the guys at https://wxwidgets.org. What they require  need is a minimal sample, though, that reproduces the error. wxWidgets comes with many sample programs that might allow to do so. But as I don't own a mac I am not the right person to report mac bugs to them.

**Comment by perryprog** [comment] 2019-12-11 12:56
This is no longer an issue with later versions of wxWidgets. (See also #1180)

**Comment by miccal** [comment] 2020-06-17 07:42
I have installed `wxmaxima` via Homebrew (which use `wxmac` as a dependency), and I have found one way around this issue is to force wxMaxima to run in Light Mode by modifying `wxmaxima.plist` with
```
defaults write wxmaxima NSRequiresAquaSystemAppearance -bool yes
```

**Closed** 2020-12-15 05:40 UTC
Labels: Bug in external framework
