### ISSUE TITLE
Broken d01ed90 master

### ISSUE THREAD

**Issue by rend3r** [wxMaxima-developers/wxmaxima#748] opened 2016-07-17 21:47 UTC
wxWidgets: 3.1.0
Unicode Support: yes
Maxima version: 5.38.1_5_gdf93b7b_dirty 
Lisp: SBCL 1.3.5

Every 2nd document evaluation (evaluate all cells) leads to the error:
Message from maxima's stderr stream: STYLE-WARNING: Undefined alien: "win32_wait_for_two_objects_or_signal"

**Comment by gunterkoenigsmann** [comment] 2016-07-18 05:52
All I could find about this error was https://groups.google.com/forum/#!topic/sbcl-help-archive/nR9I3wQjMo8
It seems to indicate that this might be a bogus warning issued by sbcl. If it happens every 2nd time I assume it to be somehow timing-dependent... Don't know if the maxima team knows more about what could cause this warning. Will ask them, though.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment] 2016-07-18 06:02
Asked the maxima developers: https://sourceforge.net/p/maxima/mailman/message/35226511/ 
Let's see  what their answer is.

**Comment by rend3r** [comment] 2016-07-24 18:41
Wolfgang Dautermann's build from SF is not affected
wxMaxima version: 16.4.2
Maxima version: 5.38.1_5_gdf93b7b_dirty
Maxima build date: 2016-05-13 22:35:09
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.5

**Comment by gunterkoenigsmann** [comment] 2016-07-25 04:36
Weird! But it just might be that on your system it uses a different timing than your build.

**Comment by rend3r** [comment] 2016-07-26 19:25
>on your system it uses a different timing than your build.

What do you mean under "different timing"?

**Comment by gunterkoenigsmann** [comment] 2016-07-26 20:37
My guess (but it is only a guess) was the following:
- The error is clearly in sbcl or in maxima
- but it is triggered by a specific version of wxMaxima that doesn't do anything different to the things the other version that doesn't trigger the problems does do => The problem cannot be that wxMaxima is doing a wrong thing
 - and the problem doesn't happen every single time. This means it might either depend on use of noninitialized memory that might happen to accidentally contain the right data - or it is hard to trigger because it can only be triggered by doing something in the right fraction of a second.

The only solution for this I was able to think of was that your and Wolfgang's Version of wxMaxima do the same thing - but that one of these versions is a little bit faster. Therefore maxima is started, connects to wxMaxima using a network connection, wxMaxima is sending the first data packet to maxima - and something doesn't work if this happens in the wrong moment. One scenario would be that first the network connection is opened and then the action what has to be done if a data packet arrives over the network is defined => if the data arrives too early it arrives before sbcl has decided what to do with data. But as this is only a guess I might be completely wrong here.

Kind regards,

 Gunter.

**Comment by KubaO** [comment] 2020-07-10 19:25
Closing as this doesn't really reproduce.

**Closed by KubaO** 2020-07-10 19:25 UTC
Labels: bug
