### ISSUE TITLE
Unreadble text

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1235] opened 2020-03-25 12:44 UTC
What happen here (tonight nightly build 2020-03-25)
![image](https://user-images.githubusercontent.com/2638713/77537603-a9bf5c00-6e9e-11ea-9fa4-d84694cfee2e.png)

**Comment by gunterkoenigsmann** [comment] 2020-03-25 21:26
My hope is that you have tried to set a font to "symbol" or "dingbats" in the config dialogue in order to see which font is affected and now that many bugs in the style code have been fixed that started to be effective with a few year's delay.

**Comment by ReneSci** [comment] 2020-03-27 11:19
Yes - the Default font was set to some strange symbols-font.  Setting it to e.g. Century (11) helped quite a bit.  (tonight nightly build 2020-03-27).
Is it correct that I couldn't find a font setting for Maxima output ?

**Comment by KubaO** [comment] 2020-07-10 16:43
Can you please check this again using the master branch or the nightly? It's very important that it gets fixed.

**Comment by KubaO** [comment] 2020-07-16 06:36
@ReneSci  Could you please test this using the master branch or nightly build? If that's not possible, please attach - to this issue - the document you used to produce the erroneous output. I'll have no choice but to close this issue otherwise, since I don't know how to reproduce this problem. With all defaults in place, it works for me.

**Comment by KubaO** [comment] 2020-08-27 08:09
I believe that this problem has been fixed now, through changes in the style system and the font defaulting.

**For anyone else who might have a similar issue: explicitly set the Default and Math Default text fonts - it's likely that your old settings might result in fonts that are present but not very usable.**

**Closed by KubaO** 2020-08-27 08:09 UTC
Labels: bug, needs-more-info
