### ISSUE TITLE
Windows: The path to the maxima binary ends with wxmaxima.exe/maxima/maxima.bat

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#579] opened 2015-09-30 17:52 UTC
Did see this on 3 PCs. Astonishingly maxima is still running fine on these computers.

**Comment by KubaO** [comment] 2020-07-10 18:42
I can't reproduce it; seems fixed in master.

**Closed by KubaO** 2020-07-10 18:42 UTC
Labels: bug
