### ISSUE TITLE
Underscores not converted to subscripts

### ISSUE THREAD

**Issue by m-weirich** [wxMaxima-developers/wxmaxima#1584] opened 2021-09-17 13:43 UTC
wxMaxima 21.x doesn't convert underscores to subscripts properly. In the below example t_ONmax and t_OFFmax should be displayed with subscript.
![grafik](https://user-images.githubusercontent.com/89512797/133791991-e6be5c60-564f-4878-beb6-ef2a4afc81bb.png)
Couldn't detect a scheme so far, which underscores are converted to subscript and which ones not.
Older versions like 17.05.0 displays the same formula (and of course all others as well) correctly:
![grafik](https://user-images.githubusercontent.com/89512797/133791833-d7ec91e0-8fb1-4d03-a00c-d6b1a81e5df6.png)

wxMaxima version: 21.02.0_MSW
using wxWidgets version: wxWidgets 3.1.4
Maxima version: 5.45.1
Maxima build date: 2021-06-21 17:43:28
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0

**Comment by daute** [comment] 2021-09-18 08:28
Strange, can't reproduce it here - neither on Linux (21.02.0 and current development version) nor on Windows (21.02.0, included in the latest Maxima release).

**Comment by m-weirich** [comment] 2021-09-18 18:54
Definitely no options set. And I loaded exactly the same file into 21.x and 17.x, where it works as expected.
It becomes even more strange when you look at the example below:
![grafik](https://user-images.githubusercontent.com/89512797/133905390-099d57b1-a3cc-4f85-b169-a360b53f3826.png)
If I change P_OUT to P_oUT, subscript works as it should:
![grafik](https://user-images.githubusercontent.com/89512797/133905431-df6d94be-dc6b-474c-b6a6-b0516334a56c.png)
Other changes work as well:
![grafik](https://user-images.githubusercontent.com/89512797/133905463-e19f5225-77a2-442b-bec2-539af8a7caf7.png)
I tried many more. Seems there is something special about 'OUT'.
When you examine the XML output of Maxima (Raw XML Monitor) you'll find that P_OUT creates a different XML code than for example P_OUT1.

**Comment by gcem** [comment] 2021-09-20 08:13
Does this happen if you write the command right at the beginning of a new session?

**Comment by daute** [comment] 2021-09-20 11:10
> wxMaxima version: 21.02.0_MSW
> using wxWidgets version: wxWidgets 3.1.4
> Maxima version: 5.45.1
> Maxima build date: 2021-06-21 17:43:28

Concerning the version number - included in the precompiled installer, I made (and I am pretty sure, that one was used, the build date and time is exactly the same as in that installer), included is not wxMaxima 21.02.0 but 21.05.2:
`wxMaxima version: 21.05.2_MSW`
Maybe a typo? Am I right? Or did you use an older wxMaxima version, not the included one?

And - as gcem wrote (I assume the error is not reproducible too) - maybe you can construct a minimal (problematic) example and attach it to the bug report.
Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment] 2021-09-20 13:03
What is the value of the maxima variable `wxsubscripts`? And what does the XML monitor (double-click on the network symbol in the bottom right) show if somethin isn't auto-subscripted that should?

**Comment by m-weirich** [comment] 2021-09-20 19:50
_Does this happen if you write the command right at the beginning of a new session?_
No, it doesn't happen if it's the very first command. 
![grafik](https://user-images.githubusercontent.com/89512797/134063521-5e657b5a-c3be-454e-b95f-7018cc8e8823.png)
I found that the issue occurs only and  only affects varaiables that have been assigned before.
For example if P_OUT is defined as below and then used in a subsequent equation, there will be no subscript:
![grafik](https://user-images.githubusercontent.com/89512797/134064996-4c49841e-4a44-4707-9bea-c95f80a01dfc.png)
With the above example it should be possible to reproduce the issue.
And again, **exactly** the same sequence of expressions works absolutely fine in older version:
![grafik](https://user-images.githubusercontent.com/89512797/134065251-6d6d6dc8-885e-485f-8845-ba70973aa85a.png)
Finally: 21.02.0 is correct, maybe a relic of older Maxima version. I nevertheless confirmed the issue on two other computers with 21.05.2 as well.

**Comment by gunterkoenigsmann** [comment] 2021-09-21 03:16
Gaaah! That looks like we'll need a lisp wizard: The autosubscript code is part of wxmathml.lisp.

**Comment by robert-dodier** [comment] 2024-08-26 05:51
Problem reported here is fixed by same patch as submitted for #1807 . I'll leave this open until someone can build a new version, then we should come back to this one and close it.

**Comment by robert-dodier** [comment] 2024-08-31 22:01
I pushed commit [ a22f5a3 ] which fixes the problem described here.

**Closed by robert-dodier** 2024-08-31 22:01 UTC
