### ISSUE TITLE
edit configure

### ISSUE THREAD

**Issue by zmth** [wxMaxima-developers/wxmaxima#1256] opened 2020-04-24 03:15 UTC
build_info(version="5.43.0",timestamp="2019-06-01 18:55:31",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="1.4.14",maxima_userdir="C:/Users/zmth/maxima",maxima_tempdir="C:/Users/zmth/AppData/Local/Temp",maxima_objdir="C:/Users/zmth/maxima/binary/5_43_0/sbcl/1_4_14",maxima_frontend="wxMaxima",maxima_frontend_version="19.05.7")
--------------------------------------------------------------
Every time open maxima go to configure and it DOES NOT HAVE what i selected as defaults for font and in style it always comes back with for example 'Bold' and 'Italic' checked which i DON'T want but no matterwhat when i uncheck them, save it, load, anything it always comes back again with those checked and also NOT what i selected for fonts. Also what i have selected as fonts in other areas it does not save and comes back as if most if not all the changes i made were not saved. Seems the file in question is system.ini but i am not sure if the problem is elsewhere. Also cursor choose font is greyed out and i want it large and bold maybe even different color as it is NOT prominent enough and sometimes hard to locate or see. Also wrap long output expressions only has for text so where do i choose to wrap math output display? And how do i get it to view one screenful at a time without using the mouse page down scrolls down one view NOT the bottom of the previous view as it should? Somehow the output script or style got changed to bold italics how do i get it back to non italics and non bold and set math font did not help. On configure what is the difference between worksheet and style?

**Comment by Kaiser1401** [comment] 2020-05-06 09:44
seems to be related to #1103

**Comment by KubaO** [comment] 2020-06-01 06:51
This simply doesn't work, so there's nothing you can do about it. Once it's fixed, it'll work as one would expect. Please do not mix different problems together: feel free to open other issues for things unrelated to the style system.

This is related to broken font handling in the style system. A fix is in the works as a part of the first round of text style system cleanups. This is a known issue and I can reproduce it easily.

**Comment by KubaO** [comment] 2020-07-09 05:42
There were two parts of it:

1. Wrapping: it's better, but there are still bugs left, I opened #1329.

2. Configuration: This now works, with one exception: on Windows, wxWidgets shows the font selection dialog in hi-dpi mode, but the rest of wxMaxima is not in hi-dpi. This breaks the wxMaxima -> font dialog transfer of font size: it is shrunken on the way into the dialog. However, it is correct when returned from the dialog.

  I could work around with a hack that checks the DPI status and pre-scales the font, but this would be ugly and won't fix the root of the problem. Thus, that part is #1287.

These issues are blockers for 20.07. I'm closing this one, since the two issues mentioned above should take care of the remaining work. If there's anything else, please open a new issue.

**Closed by KubaO** 2020-07-09 05:42 UTC
Labels: bug, confirmed
