### ISSUE TITLE
The problem of subscripts display still persists

### ISSUE THREAD

**Issue by idealkindom** [wxMaxima-developers/wxmaxima#1754] opened 2023-02-18 10:00 UTC
with the latest version of WxMaxima 23.05.01, tested on Win X64 pro PC.
Maybe the problem could be repeated with the following text typed in a WxMaxima window:

kill(all)$
ΔP_r;print(ΔP_r,"=",4.6,".")$
ΔP_r1;print(ΔP_r1,"=",2.3,".")$
ΔP_r[1];print(ΔP_r[1],"=",1.2,".")$
P_r;P_r:4.6;print('ΔP_r,"=",4.6,".")$
P_r1;P_r1:2.3;print('ΔP_r1,"=",2.3,".")$
kill(all)$
P_r[1];P_r[1]:1.2;print('ΔP_r[1],"=",1.2,".")$

Until now, as I tried, only WxMaxima 19.05 gives the best outputs of subscripts.

**Comment by idealkindom** [comment] 2023-02-25 17:08
I attached a screenshot to show the problem.
<img width="326" alt="Snipaste_2023-02-26_01-07-19" src="https://user-images.githubusercontent.com/18344868/221370130-8020ea4c-bd84-4b06-ac2e-ec06d32598aa.png">

**Comment by gunterkoenigsmann** [comment] 2023-03-05 10:36
From time to time I try to get the maxima project to help me write a lisp macro that sets properties that survive a kill(). But until now they didn't help me in this respect and currently we have no lisp programmer available who can help us out here.

**Comment by idealkindom** [comment] 2023-03-07 16:19
> From time to time I try to get the maxima project to help me write a lisp macro that sets properties that survive a kill(). But until now they didn't help me in this respect and currently we have no lisp programmer available who can help us out here.

I tried to comment the line of "kill()" but the subscript rendering problem in the output persists.

**Comment by idealkindom** [comment] 2023-07-19 12:39
> From time to time I try to get the maxima project to help me write a lisp macro that sets properties that survive a kill(). But until now they didn't help me in this respect and currently we have no lisp programmer available who can help us out here.

Hi，Gunter Königsman,I tested the latest release of Maxima with wxMaxma 23.05.01 and the nightly made Maxima, the problem of subscript display is still there. It's very strange that this problem appear after Maxima version 5.43.

**Comment by robert-dodier** [comment] 2024-08-26 05:00
Looks like this ticket is a duplicate of #1807 . Closing this one accordingly.

**Closed by robert-dodier** 2024-08-26 05:00 UTC
