### ISSUE TITLE
Formatting seems off.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1894] opened 2024-02-21 22:33 UTC
The formatting in the build_info and the myinfo() I made is incorrect.
My function needs to be run twice.  Before it works.
The second items in the list should line up on a vertical line.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/76ee0f40-2e1b-44ca-a3ab-e3a2eed99d36)

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/4ce967c0-6903-408e-ac68-35736dc72914)

[wxmaxima-init.txt](https://github.com/wxMaxima-developers/wxmaxima/files/14365852/wxmaxima-init.txt)
Attached is the function myinfo() which should load each time WxMaxima is opened up.

**Comment by richardgobeli** [comment] 2024-02-23 05:26
There must be something off with the font size.
Today the second items line up in a vertical column.
But myinfo() still does not work the first time.
I see this is a version before the above.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/04efd52c-63ac-40d9-814d-f1a4a1e6001d)

Here it is from today.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/e9bc8247-f1a0-40e8-9705-ae7d82d7cb2d)

**Comment by daute** [comment] 2024-02-23 08:21
I think the reason is, that your function `myinfo2()` has some "side effects" (printing) during evaluation. And I suspect, that this output - I am really guessing - reaches wxMaxima 'too early'.

A improved version of your function may be:

```
myinfo2():=block(buildinfo:build_info(),
listx:["maxima version","time stamp",host,"lisp name","lisp version","maxima directory","temp directory","obj directory","front end name","front end version"],
myinfooutput:printf(false, "------------------------------~%"),
for i: 1  thru 10 do myinfooutput:sconcat(myinfooutput,printf(false, "~35a~a~a~%", listx[i], "= ", part(buildinfo,i))),return(myinfooutput));
```

(That can be improved, by using local variables, etc.)

Then the output of the function is the (formatted) result, which can either be printed (`myinfo2();`) or assigned to another variable (`a:myinfo2()$`) and than you can use `a` for further processing.

Best regards, Wolfgang

**Comment by daute** [comment] 2024-02-23 08:23
Concerning the alignment: That (of course) will only work, if you use a monospaced font.

**Comment by richardgobeli** [comment] 2024-02-24 02:20
This had always worked a few months ago.  Now it does not work on the first try.

**Comment by richardgobeli** [comment] 2024-02-24 05:10
I tried your version with the same result every time nothing;
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/4df49ee1-66f1-4724-8cc9-7ba5f89528fd)
Printing direct works but only the second time.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/7415d0c2-9b14-4d27-908a-6259f835b164)

**Comment by richardgobeli** [comment] 2024-02-24 06:05
why is this?  on starting a normal printf takes more the 5 seconds and does not do a line feed, but the second time it is very fast and does the new line.
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/a7f7c332-f562-4e82-a8fb-14d01b36cbce)

**Comment by daute** [comment] 2024-02-25 09:09
Hm. Strange, you are right, my function works on Linux (where I tested it), but not on Windows, it removes the newlines - but only if wxMaxima is used as frontend.
There  is something very strange occuring most likely in the Lisp part of wxMaxima. But what?

**Comment by gunterkoenigsmann** [comment] 2024-02-25 14:18
If the problem might be the stupid CR/CRLF/LF/LFCR problem?

**Comment by gunterkoenigsmann** [comment] 2024-02-25 14:24
My question is now: Did maxima send one line containing all the minusses the first time the command was issued and two lines with half the minusses each, the second time?

The problem with the symbol table is that that table is 65 Kilobytes long - and reading from maxima for some reason is quite slow. Am still trying to find out how to speed it up.

**Comment by gunterkoenigsmann** [comment] 2024-02-25 14:38
Found one reason why reading unicode from a socket was able to be this slow. Originally I tried to move it to a background thread. But that still doesn't work as it should, for some reason...

**Comment by richardgobeli** [comment] 2024-02-27 14:21
New result from last nights build.  About 50% of the time it will do this from repeated restart button.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/1ab0f8ac-7897-4ea8-8ae2-e399bb9652a2)
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/bfac820a-3d16-403c-bab7-0b60a49b4246)

**Comment by gunterkoenigsmann** [comment] 2024-02-28 04:22
With that command I was finally able to reproduce the bug on my own computer. Thanks a lot for doing all the debugging work!

**Closed** 2024-02-28 04:23 UTC
