### ISSUE TITLE
Maxima help button opens "file not found" 

### ISSUE THREAD

**Issue by robert-dodier** [wxMaxima-developers/wxmaxima#1621] opened 2022-01-24 04:56 UTC
Migrating this item from: https://sourceforge.net/p/maxima/bugs/3925/

Please note that I (Robert Dodier) am not OP; instead that's https://sourceforge.net/u/maximauser4837/ .

OP writes:

I am using Maxima v5.45.1, and whenever I open Maxima Help under the Help tab on the top bar, it opens the incorrect path (D:/maxima-5.45.1/bin/share/maxima/5.45.1/doc/html/maxima_singlepage.html), which shows a "File not found" error.
I found that the correct path is at D:/maxima-5.45.1/share/maxima/5.45.1/doc/html/maxima_singlepage.html (notice that the /bin is omitted).

I am using Windows 11, and the wxMaxima user interface. The manual is present on my system, but the location the Maxima Help button tries to open is invalid:

D:/maxima-5.45.1/bin/share/maxima/5.45.1/doc/html/maxima_singlepage.html (path to file that opens in browser, returns "file not found")

D:/maxima-5.45.1/share/maxima/5.45.1/doc/html/maxima_singlepage.html (actual location of file)

In addition, there is no D:/maxima-5.45.1/bin/share/ folder present on my system whatsoever.

**Comment by daute** [comment] 2022-01-31 06:50
The bug reporter is right, I reproduced it now in a virtual machine with 2 disks. The strange thing: It **does** work, when installing to the default path `c:\maxima-5.45.1`, it does not work, when installing to `d:\maxima-5.45.1` - will fix that until the next release. Until now, the workaround is to install to the default path.
Sorry for that & best regards, Wolfgang

**Comment by daute** [comment] 2022-01-31 22:21
It seems, the reason was, how Maxima reported the installation prefix (only when **not** installed in the default path). Should be fixed with commit https://sourceforge.net/p/maxima/code/ci/a850abd0ebc2ce8d9afe122a2a5cdfabe93e8f9f/ (in the Maxima source code. See details there).
Best regards, Wolfgang

**Closed by daute** 2022-01-31 22:21 UTC

**Comment by gunterkoenigsmann** [comment] 2022-02-08 20:33
Looked at the wxMaxima code: wxMaxima tries to open the manual from `*maxima-infodir*. Will as a second way to fix this bug canonicalise the path to that directory.
