### ISSUE TITLE
Re-Evaluate all hangs Maxima on the Windows MinGW-Build

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1375] opened 2020-08-18 10:46 UTC
Seems to be a regression:

- Type in any mathematic command
- press Ctrl+R

=> 2 Cells in evaluation queue for an indefinite amount of time.

**Comment by KubaO** [comment] 2020-08-18 15:41
The likely cause for this is UTF8 decoder changes. I can fix this as long as the build is coming from CI, and as long as that CI can produce new builds in <15 minutes. In other words, if this happens on our AppVeyor build, then I can fix it. In fact, there's no good reason why we don't run tests on AppVeyor builds - both MSVC and MinGW. We should. The build would need to download and install Maxima, *but this should be done as a background task so that the build would proceed in parallel*.

**Comment by KubaO** [comment] 2020-08-18 19:05
Cool, I can reproduce it under a MinGW 8.1 build using the MinGW bundled with Qt, thus no extra installs. Nice.

**Comment by gunterkoenigsmann** [comment] 2020-08-18 19:18
That is really great news since until now much of the windows development was made in a big trial-and-error-with-one-try-per-day attempt.

---

If you could make our tests run on appveyor, too, that would be extremely cool - but AFAIK appveyor doesn't provide us with an user session which means we cannot open windows during the test: https://help.appveyor.com/discussions/questions/678-gui-unit-testing-in-appveyor 

Don't know if that is still the case, though, and if a real windows wizard needs such a session...

**Comment by KubaO** [comment] 2020-08-18 19:38
I think that things have changed on AppVeyor since 2014, but I haven't checked this with wxMaxima yet.

Anyway, this is another one-liner. Fixed with 94702eee

**Closed by KubaO** 2020-08-18 19:38 UTC
