### ISSUE TITLE
Save cells in logical order

### ISSUE THREAD

**Issue by groszdaniel** [wxMaxima-developers/wxmaxima#587] opened 2015-10-07 00:45 UTC
Currently, the cells are saved in the display order: if you start a new cell above an existing cell, it will be saved before it. Also, if any cells are deleted, they are not saved. This makes it impossible to replay the file if it contains references like %, or %i86.

The cells should be saved in imput order (incl. deleted cells), ideally with annotations as to which ones to display and in what order.

**Comment by gunterkoenigsmann** [comment] 2015-10-07 05:50
Maxima's reference manual actually provides kind of what you want even 
(given that it is >> 1000 pages long) if it is sometimes unavoidable to 
ask. Just type in:

      playback();

The problem is that if you evaluated cells in a different order there 
is no obvious way to determine which of the comments, chapter or 
section headings is to be assigned to which cell. Also when a cell that 
has been modified and re-evaluated or a cell that has been evaluated 
three times in a row actually it is hard to tell if this actually needs 
to be done in order to get the right result.

I personally have grown to like wxMaxima's worksheet approach that 
allows you to debug everything by temporarily adding a few experimental 
lines of code at any place just to see the outcome without having to 
wait until the program has re-evaluated the whole file once again. The 
drawback of this approach is naturally, that if you are unlucky it 
might be hard to find out which of the now-deleted cells actually was 
important.

**Comment by gunterkoenigsmann** [comment] 2015-10-07 06:11
Did find a thing in the documentation that might be useful for 
automatizing playback():


       writefile("LastSession.txt");
       playback();


Kind regards,

     Gunter.

**Comment by groszdaniel** [comment] 2015-10-07 22:02
Well, I've found the writefile command, but it was too late when I already had hundreds of lines on my worksheets. I'll try to remember to do it at the beginning of every session. Of course then the display order (and which cells to display at all) will not be remembered.

The display order of the lines, and which lines to display (a line which was evaluated 3 times would be stored as 3 lines of which only the last is displayed), and the location of section headers could be stored in additional comments. Replay could be slower, but at least it would work. Alternatively, cells could be stored in display order (again, including cells which were deleted or modified later), with comments storing the evaluation order and which cells to display.

**Comment by gunterkoenigsmann** [comment] 2015-10-08 05:10
Normally the writefile() should write the output of a playback() to the 
file... ...at least according to maxima's manual. If that works you 
could add these two commands to the end of a file and automatically get 
a log at the end of a session.

---

Writing notes on the left margin of the page would look like word's 
"record changes" feature but in my case wouldn't help much: I often 
change the contents of cells during debugging - and don't tend to 
evaluate cells out-of-order if no debugging is needed.

Another idea: Perhaps it would make sense for you if we implemented a 
way to save the contents of the "history" sidebar along with the file.
I currently cannot think of a way of doing so without breaking the 
compatibility with the old .wxmx format - except of...
...technically the .wxmx file is  nothing but a .zip file with a 
different name. It would perhaps be possible to add a file to the .wxmx 
file that contains the contents of the history sidebar...

Kind regards,

    Gunter.

**Comment by groszdaniel** [comment] 2015-10-08 15:10
Ah, I get the playback thing now.

**Comment by KubaO** [comment] 2020-07-10 20:06
I believe that this could be classified as a feature request to optionally use `writefile()` and `playback()`. Perhaps this should be a per-document setting instead of a global configuration setting...

**Comment by gunterkoenigsmann** [comment] 2020-07-11 01:40
The problem I had (which hindered me from implementing that function) was if I save the commands that were executed in the order they were executed: Where do I put the comment, image and sectioning cells?

Perhaps I should add a "save as .mac" tight-click menu option to the history sidebar?

**Comment by KubaO** [comment] 2020-07-11 03:21
I’d say that the History context menu seems good, but should be also in File menu to be discoverable (Export History or something like that - no strong opinions here).

**Closed** 2020-07-11 13:26 UTC
Labels: feature request
