### ISSUE TITLE
Printing to a printer with windows 10

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1406] opened 2020-10-02 20:11 UTC
[DOC100220-10022020150305.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/5320028/DOC100220-10022020150305.pdf)
This is what I get when printing a few matrices.  It does the same printing to a pdf.

It does work when printing to html and then to pdf.
as below:
[untitled.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/5320055/untitled.pdf)

**Comment by KubaO** [comment] 2020-10-02 22:13
This is probably related to the “it’s turtles all the way down” wasps-nest of problems with propagating positions and sizes during recalculation. I have a major change that should permanently make such bugs impossible by design but I’m still working on it. The idea would be to get it merged before the end of October so that a major robustness increase would be had for the holidays :)

**Comment by gunterkoenigsmann** [comment] 2020-10-08 08:25
I believe that I accidentally broke this - and have accidentally fixed it again yesterday => I don't own a Windows 10 but I believe printing should work now again.

**Comment by richardgobeli** [comment] 2020-10-10 17:35
I'll check it.

**Comment by richardgobeli** [comment] 2020-10-10 21:23
This is how it looks in the WxMaxima window.
![image](https://user-images.githubusercontent.com/31253976/95665281-8bf0d600-0b14-11eb-93fc-5f90171849d9.png)
It now prints OK for most of the file but the integral as a noun is very big.
[Printing wxMaxima document.pdf](https://github.com/wxMaxima-developers/wxmaxima/files/5360199/Printing.wxMaxima.document.pdf)

**Comment by gunterkoenigsmann** [comment] 2020-10-15 20:46
Should be resolved by c17fe257b..d39375fdf

**Closed by gunterkoenigsmann** 2020-10-15 20:46 UTC
