### ISSUE TITLE
Runtime error on start: Locale not valid

### ISSUE THREAD

**Issue by Groctel** [wxMaxima-developers/wxmaxima#1430] opened 2020-11-11 09:09 UTC
I'm running wxmaxima 20.09.0-1 in my Arch Linux machine and it crashes on start with the following error message:

```
➜ wxmaxima                                                  
09:37:33: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1013,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8).

(wxmaxima:2917): Gtk-WARNING **: 09:37:34.432: Negative content width -5 (allocation 1, extents 3x3) while allocating gadget (node scale, owner GtkScale)

(wxmaxima:2917): Gtk-CRITICAL **: 09:37:34.432: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScale

(wxmaxima:2917): Gtk-WARNING **: 09:37:34.548: Negative content width -5 (allocation 1, extents 3x3) while allocating gadget (node scale, owner GtkScale)

(wxmaxima:2917): Gtk-CRITICAL **: 09:37:34.548: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScale
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
[1]    2917 abort (core dumped)  wxmaxima
```

Version 20.07.0-1 is the latest that doesn't crash.
However, running with `-u 20.07.0-1` doesn't start maxima, stating that the most probable cause is that it isn't installed.
Here's my package list if it's of use: https://paste.ubuntu.com/p/FkwvXd6bKS/

**Comment by gunterkoenigsmann** [comment] 2020-11-12 06:01
That looks like it isn't a issue in the code, but that somehow the wxWidgets and glibc library versions that are installed on your computer don't match the one wxMaxima was compiled with.
I unfortunately don't know enough about archlinux to know how that might have happened, though.

**Comment by antonio-rojas** [comment] 2020-11-22 10:48
The mismatch warning has nothing to do with the problem. This is caused by the hardcoded en_US locale in 
https://github.com/wxMaxima-developers/wxmaxima/blob/master/src/StreamUtils.cpp#L62
which does not need to be available in all systems, causing a crash.

**Comment by gunterkoenigsmann** [comment] 2020-11-22 11:12
@KubaO : Can I assign this bug report to you? Looks like very advanced magic, that.

**Comment by gunterkoenigsmann** [comment] 2020-11-23 12:46
@antonio-rojas : That observation was genius! I believe I found a way around that problem. Let's hope this is correct.

**Comment by KubaO** [comment] 2020-11-23 13:05
I changed that locale a while ago I think to work both on OS-X and Windows, and it also works on our Ubuntu tests. So it’s weird that it may not exist on some system.

**Comment by antonio-rojas** [comment] 2020-11-23 13:14
It's not weird on Arch Linux, where only the locales that are explicitly enabled by the user are available. And neither on gentoo, apparently: https://bugs.gentoo.org/755626

**Comment by antonio-rojas** [comment] 2020-11-23 20:20
Unfortunately that's even worse... C.UTF-8 is an unofficial glibc extension that doesn't exist in some distributions. With en_US.UTF-8 this crashes if the locale is not enabled and you can workaround it by enabling it, now it is unconditionally broken in distros that don't patch glibc.

**Comment by KubaO** [comment] 2020-11-24 02:38
This will probably break it on OS-X. If anything, since this is a glibc extension, it must be protected by an ifdef to enable it there only.

**Comment by gunterkoenigsmann** [comment] 2020-11-24 11:55
The more I look at our options the less I find: 

- We could create a `std::locale("")` in order to get a valid locale to start with.
- then we could query that one for its name and see if it ends with UTF8.

But what if the locale we currently use is unnamed?

**Comment by KubaO** [comment] 2020-11-24 14:24
Truth is: all we needed the locale for was to reuse a stateful UTF-8 decoder that can be suspended, and I could have, instead, copied the wxWidgets code that implemented it, simplified, and left it at that. wxWidgets unfortunately hides the decoder as a private detail that is not exported out of the library. There is one or two header-only UTF-8 decoder library out there, and it could be used as well.

We don’t need the locale for anything else and it appears that there is way more trouble with it than it’s worth. I’ll take an evening to do that. In retrospect it was a bad idea to try and use it — there are way too many variants out there to make it useful. It’s also a major failing of the C and C++ spec: the locale becomes useless outside of a very narrow range of applications, because the implementations have the freedom to make it as narrow as they wish :(

**Comment by gunterkoenigsmann** [comment] 2020-11-25 10:32
I guess then this is one of the instances where I don't touch this piece of code and wait until it is fixed, correct?

---

Sometimes it is surprising how powerful C++ has grown. But sometimes it is surprising, instead, where we are left completely on our own... ...or in case of the MacOs issue how easy it is to break things during packaging or compilation, nowadays.

**Comment by KubaO** [comment] 2020-11-25 17:55
I’ll have a fix later today I hope.

**Closed** 2020-11-28 08:10 UTC
