### ISSUE TITLE
Warning is still there on Nightly build 2023-10-26

### ISSUE THREAD

**Issue by ReneSci** [wxMaxima-developers/wxmaxima#1831] opened 2023-10-27 06:30 UTC
build_info(version="branch_5_47_base_439_ga04417106_dirty",timestamp="2023-10-26 23:53:34",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.3.2",maxima_userdir="C:/Users/U265227/maxima",maxima_tempdir="C:/Users/xxxx/AppData/Local/Temp",maxima_objdir="C:/Users/xxx/maxima/binary/branch_5_47_base_439_ga04417106_dirty/sbcl/2_3_2",maxima_frontend="wxMaxima",maxima_frontend_version="23.10.0_DevelopmentSnapshot_MSW")

This warning pups up a number of times (4 times for me), otherwise wxMaxima seems to run ok
![image](https://github.com/wxMaxima-developers/wxmaxima/assets/2638713/e33a4287-42b1-4232-8380-93cac65c46d6)

**Comment by daute** [comment] 2023-10-27 15:45
You mean the warning from the issue https://github.com/wxMaxima-developers/wxmaxima/issues/1830 which was closed by me?
I can not reproduce that. "Enter Matrix" does not result in such warnings (now), neither on Windows (10, 22H2, 64bit), nor on Linux. And it did produce that warning on Linux before my commit: https://github.com/wxMaxima-developers/wxmaxima/commit/38b2ac419fa73720f82451c9a8a038c8e21b1127

Best regards, Wolfgang

**Comment by ReneSci** [comment] 2023-10-27 23:02
Hmmm... no it shows up at start up. Even with an empty worksheet.

Den fre. 27. okt. 2023 kl. 17.45 skrev Wolfgang Dautermann <
***@***.***>:

**Comment by gunterkoenigsmann** [comment] 2023-10-28 08:12
Hmm... ... oftentimes such a report is caused by MS Windows starting a different one of the installed wMaximas than the one that would be mogical. If not: the problem most probably is a debug messages sidebar message. Which message does appear after that dialogue is closed?

**Comment by ReneSci** [comment] 2023-10-29 06:14
After giving the same message 4 times, wxMaxima runs normally without further warnings.

**Comment by gunterkoenigsmann** [comment] 2023-10-29 08:08
The question was: Which message does appear in the "debug log messages" sidebar when this assert dialogue is closed?

**Comment by daute** [comment] 2023-10-29 09:51
The issue is still not solved?
And I was so happy, that I was able to get the same message here and was able to fix it (here on my system)...

Can you tell us more about your setup? Are you running a 64 or 32 bit system? Which locale (I assume, Danish?).
Are you able to run wxMaxima using the Gnu debugger (gdb) and get a backtrace?

Best regards, Wolfgang

**Comment by ReneSci** [comment] 2023-11-02 12:40
The  Debug Alert still pops up.

**Comment by gunterkoenigsmann** [comment] 2023-11-03 16:24
Nearly: the last thing we still need is you to tell the dialogue to crash wxMaxima so we end up in gdb - and to type

````
backtrace
````
In gdb which function called which function with which parameters leading to that crash: On Windows that info should come with all line numbers that are involved in the crash.

**Comment by ich-bin-der-ich-bin** [comment] 2023-11-03 17:02
Hello,

ok, I'm not familiar with gdb (or debugging at all) so please accept my apologies.
So here's the output:
#0  0x0000555555bc15eb in  ()
#1  0x0000555555bc3185 in  ()
#2  0x000055555588b864 in  ()
#3  0x000055555588c35b in  ()
#4  0x00007ffff6f86cb2 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
    at /usr/lib/libwx_baseu-3.2.so.0
#5  0x00007ffff6f878e7 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#6  0x00007ffff6f87c45 in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#7  0x00007ffff6f87cef in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#8  0x00007ffff6f87e0a in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#9  0x00007ffff75a2c2c in wxDialogBase::SendWindowModalDialogEvent(int) () at /usr/lib/libwx_gtk3u_core-3.2.so.0
#10 0x0000555555917dca in  ()
#11 0x00007ffff6f86cb2 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) ()
    at /usr/lib/libwx_baseu-3.2.so.0
#12 0x00007ffff6f878e7 in wxEvtHandler::SearchDynamicEventTable(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#13 0x00007ffff6f87c45 in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#14 0x00007ffff6f86e53 in wxEvtHandler::DoTryChain(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#15 0x00007ffff6f87e0a in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#16 0x00007ffff7687c00 in wxWindowBase::TryAfter(wxEvent&) () at /usr/lib/libwx_gtk3u_core-3.2.so.0
#17 0x00007ffff6f8a63b in wxEvtHandler::SafelyProcessEvent(wxEvent&) () at /usr/lib/libwx_baseu-3.2.so.0
#18 0x00007ffff763b23c in wxMenuBase::DoProcessEvent(wxMenuBase*, wxEvent&, wxWindow*) () at /usr/lib/libwx_gtk3u_core-3.2.so.0
#19 0x00007ffff763b343 in wxMenuBase::SendEvent(int, int) () at /usr/lib/libwx_gtk3u_core-3.2.so.0
#20 0x00007ffff7835f5f in  () at /usr/lib/libwx_gtk3u_core-3.2.so.0
#21 0x00007ffff70d06c0 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff70fea36 in  () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff70efa42 in  () at /usr/lib/libgobject-2.0.so.0
#24 0x00007ffff70efc77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#25 0x00007ffff70efd34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#26 0x00007ffff6340c9d in gtk_widget_activate () at /usr/lib/libgtk-3.so.0
#27 0x00007ffff6204edd in gtk_menu_shell_activate_item () at /usr/lib/libgtk-3.so.0
#28 0x00007ffff620521a in  () at /usr/lib/libgtk-3.so.0
#29 0x00007ffff6085039 in  () at /usr/lib/libgtk-3.so.0
#30 0x00007ffff70efb73 in  () at /usr/lib/libgobject-2.0.so.0
#31 0x00007ffff70efc77 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#32 0x00007ffff70efd34 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#33 0x00007ffff63546e5 in  () at /usr/lib/libgtk-3.so.0
#34 0x00007ffff61ee91b in  () at /usr/lib/libgtk-3.so.0
#35 0x00007ffff61ef447 in gtk_main_do_event () at /usr/lib/libgtk-3.so.0
#36 0x00007ffff6d3ab87 in  () at /usr/lib/libgdk-3.so.0
#37 0x00007ffff6d92d38 in  () at /usr/lib/libgdk-3.so.0
#38 0x00007ffff5d34f69 in  () at /usr/lib/libglib-2.0.so.0
#39 0x00007ffff5d93327 in  () at /usr/lib/libglib-2.0.so.0
#40 0x00007ffff5d35b97 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#41 0x00007ffff61ecf6f in gtk_main () at /usr/lib/libgtk-3.so.0
#42 0x00007ffff77beed6 in wxGUIEventLoop::DoRun() () at /usr/lib/libwx_gtk3u_core-3.2.so.0
#43 0x00007ffff6ed8e12 in wxEventLoopBase::Run() () at /usr/lib/libwx_baseu-3.2.so.0
#44 0x00007ffff6eb4f28 in wxAppConsoleBase::MainLoop() () at /usr/lib/libwx_baseu-3.2.so.0
#45 0x000055555585c080 in  ()
#46 0x000055555585b28b in  ()
#47 0x00005555556b5867 in  ()
#48 0x00007ffff6845cd0 in  () at /usr/lib/libc.so.6
#49 0x00007ffff6845d8a in __libc_start_main () at /usr/lib/libc.so.6
#50 0x00005555556b6715 in  ()

Just started program, clicked enter matrix and stop.

Hope (again) this will help.

Regards Michael

**Comment by ReneSci** [comment] 2023-11-09 13:40
It seems like you got it now :-)

**Comment by gunterkoenigsmann** [comment] 2023-11-09 19:12
Wow... ...wouldn't have thought that such a seemingly easy issue requires 4 pairs of eyes and lots of work from 4 human beings until it is resolved. Thanks a lot for making it possible that we finally found a fix!

**Closed by gunterkoenigsmann** 2023-11-09 19:12 UTC
