### ISSUE TITLE
Can't change language to non-default

### ISSUE THREAD

**Issue by TomasRiker** [wxMaxima-developers/wxmaxima#1103] opened 2019-03-27 21:52 UTC
Using the latest nightly version of wxMaxima (19.03.1-DevelopmentSnapshot), I can't change wxMaxima's language. When I change it to something that doesn't match my system default (German) and restart the program, it shows my selected language in the combo box, but all the GUI is still in German. The screenshot shows the state after selecting "English" and restarting wxMaxima.

![image](https://user-images.githubusercontent.com/295205/55114683-ec5f2480-50e2-11e9-98e3-77aa829af935.png)

**Comment by gunterkoenigsmann** [comment] 2019-03-28 06:45
I've no idea at all what caused this problem. But the current Nightly Build seems to resolve it, at least on linux. For windows the Nightly Build can be found at https://wolfgang.dautermann.at/maxima/nightlybuild/

**Comment by TomasRiker** [comment] 2019-03-28 07:02
It doesn't work for me (same issue).

**Comment by gunterkoenigsmann** [comment] 2019-03-28 08:24
But why does the program *again* behave differently on Windows? I never encontered these cases in the past...

**Comment by TomasRiker** [comment] 2019-03-29 08:23
It's still not working for me (nightly build from March 29th 2019).

**Comment by fthx** [comment] 2019-04-07 06:48
Same issue, running :
19.04.1-27~201904060831~ubuntu19.04.1

**Comment by gunterkoenigsmann** [comment] 2019-04-07 09:39
On Ubuntu I cannot reproduce this. Which system and Maxima language have you selected?

**Comment by fthx** [comment] 2019-04-07 09:56
OS : French
WxM : English

**Comment by TomasRiker** [comment] 2019-04-08 08:31
I haven't tried it yet, but I doubt this solves the problem. Remember that wxMaxima didn't allow me to switch to *any* other language, not just English. For example, it didn't work for Spanish either, always showing up in German, which is my system's default language.

**Comment by TomasRiker** [comment] 2019-04-09 08:42
The issue is not fixed for me. I still can't get wxMaxima to use anything but German.

**Comment by fthx** [comment] 2019-04-09 08:57
Same here.
And I get today HUGE icons in config options window :-)

**Comment by gunterkoenigsmann** [comment] 2019-04-10 05:50
Thanks a lot in advance!

wxMaxima doesn't do too much, actually: It initializes a wxLocale structure, then tells wxWidgets to use this structure to get the language from and wxMaxima also tells wxWidgets about additional places it can search for translations in.

The problem is that since that happens before any window is created the debug messages will appear on the console, not in the debugging sidebar. No idea how easy it is to access them on Ms Windows. In Linux they should appear in the terminal, if wxMaxima is started from there.

**Comment by fthx** [comment] 2019-04-10 06:49
With the latest PPA update, the issue is gone. Thanks !
In Ubuntu's console : 
```
08:43:30: Debug: wxMaxima's locale is set to to en_GB
08:43:30: Debug: Setting maxima's locale to en_GB.UTF-8.
```

Please note that I did some langpacks normal updates before that. Don't know if it's related.

**Comment by TomasRiker** [comment] 2019-04-10 07:49
The issue is solved for me in the latest nightly! Great!

**Comment by gunterkoenigsmann** [comment] 2019-04-10 17:17
Thanks for all the testing!

The current nightly build sometimes hangs during evaluation: Tried to speed up evaluation. Will try to resolve this until tomorrow.

**Comment by fthx** [comment] 2019-04-10 20:06
Yes there is something fishy here. Since some (?) time, eval get stuck until I move the window or scroll the view. Whatever is the eval, even a simple 7655-557 e.g.

**Comment by Hale812** [comment] 2019-12-17 00:42
I have the same issue in freshly installed wxMaxima 19.05.7 x64 on Windows 7x64.

The installer is forced in Japanese regardless of Location, Format, or non-unicode language (I used applocale to bootstrap the installer into English, being in Japanese environment).

After installing, the UI is Japanese, but the language shown in config menu is POLISH (!).
Changing the language there do nothing. Completely nothing. I think, some dependencies are broken again in Windows build

**Comment by Hale812** [comment] 2019-12-17 01:01
P.S. if the GUI config is broken, please tell a workaround, how can we change all the locales manually? What are the commands, where are configs are located?

**Comment by gunterkoenigsmann** [comment] 2019-12-17 18:04
At least that I can do: If you uninstall your maxima+wxMaxima and install the one from https://wolfgang.dautermann.at/maxima/nightlybuild/ instead this problem should no more affect you.

**Comment by gunterkoenigsmann** [comment] 2019-12-17 18:05
Wait: The problem is still here with Wolfgang's Nightly Build?

Will investigate that tomorrow...

**Comment by gunterkoenigsmann** [comment] 2019-12-17 18:05
Are you sure that your computer is the wxMaxima installed from https://wolfgang.dautermann.at/maxima/nightlybuild/ and not an old version?

**Comment by Hale812** [comment] 2019-12-17 23:40
Yes. I got it there yesterday, and the problem is there as well, as in "stable" build

**Comment by Hale812** [comment] 2019-12-17 23:41
Can you tell me the steps to change the UI language manually?

**Comment by gunterkoenigsmann** [comment] 2019-12-18 01:54
wxMaxima like every other windows application stores its config data somewhere in the registry. One key you can search for to find the location in regedit is

     fixReorderedIndices

The language number should be saved there in a registry key named "language". ButI don't know which number means what.

---

Perhaps I've found a possible cause for the problem persisting: wxmaxima.exe has moved to a new place in the c:\maxma-current directory a while back. Might it be that your system now contains more than wxmaxima.exe in this directory and you are still using the old one?

**Comment by Hale812** [comment] 2020-01-09 00:12
No, I installed it on a clean Windows 7 system. There was nothing before that. Just a Japanese localized windows (which is a real pain). So it starts in Japanese, which creates even more trouble for work.

**Comment by Hale812** [comment] 2020-01-09 00:32
And, I tried changing the "language" parameter in HKCU\Software\wxMaxima, and it has no effect on UI. Just the dialog resets to default, when I try changing it.

**Comment by Hale812** [comment] 2020-01-15 05:51
Dear Gunter, I am not sure what it was above (c432e89), but I downloaded the newest Wolfgang's build, and the problem is still there.
BTW. The bug seems to be similar to the language problem in PRE-5.42 versions. I tried downloading old builds, and could not change the language. In 5.42.2 I can change the language, but there are fonts are broken in Win build, making integrating impossible. Help location is also broken there.

Still need a solution for English in localized(forced by vendor/administrator) Windows. I can not read all the math words in Japanese.

**Comment by Hale812** [comment] 2020-01-15 06:37
BTW, options like "show % before _i_ and _e_" also fail. Probably, the whole config is dysfunctional.

**Comment by Kaiser1401** [comment] 2020-05-06 09:40
I have the same problem. I had a look with Microsofts process monitor on what happens in the Registry. Indeed the keys  that are created by closing the preferences dialog are only ever read when opening that dialog. they are completely ignored when starting the program and just the systems' preferred language is used (i can see the registry read for that)

**Comment by KubaO** [comment] 2020-07-10 20:47
Unfortunately, this won't happen before 20.07 is out. But soon thereafter.

**Closed** 2020-08-14 07:25 UTC
Labels: bug
