### ISSUE TITLE
Problem of copying results to Word

### ISSUE THREAD

**Issue by idealkindom** [wxMaxima-developers/wxmaxima#1942] opened 2024-08-25 13:07 UTC
The recent new version of WxMaxima has various problem hindering me from using it as normal Maxima interface.

Today I outlined some bug I confronted in copying the math results to a word docu.

No. 1 the subscript display problem, may be almostly sovled by @robert-dodier in Issue #1807;
No.2 the loss of squre number;
No.3 the intorcution of nonsense “”.
No. 4 wrong display of centered dot multiplication operator.
No.4 wrong display of “aqqrox” as a strange squre.

I attached the wxmx sheet(the archived zip file) and the word docu with pasted calculated results at the end so as to help with reproducing the problems I listed above.
Though not be a developer,  I have been doing Algebra and calculation with Maxima for more than 10 years. Until now, I think WxMaxima 19.05.7 is the last version with genearally most function stable.

[Problem on Copying results to word.docx](https://github.com/user-attachments/files/16740346/Problem.on.Copying.results.to.word.docx)
[Diaohuan-GB 50010-2010.zip](https://github.com/user-attachments/files/16740350/Diaohuan-GB.50010-2010.zip)

**Comment by idealkindom** [comment] 2024-08-25 13:08
The comparion of copying and pasting the same piece part of the calculation results could be viewd in the Word docu clearly.

**Comment by robert-dodier** [comment] 2024-08-26 03:28
@idealkindom Thanks for the additional example. I have downloaded Diaohuan-GB 50010-2010.zip and opened the wxmx document in it. I think that the problems you are encountering are mostly not bugs in wxMaxima.

No. 1, subscript display problem: that is a bug, and I have submitted a bug fix as you know.

No. 2, loss of square number: the problem is that the font does not have the superscript 2 sign, it appears. Can you switch to another font and try it again?

No. 3, nonsense " ": I don't see extra quote marks; can you point out exactly where the extraneous quote marks are appearing?

No. 4, wrong display of centered dot: I see that multiplication is displayed as an asterisk instead of a centered dot. Can you go to Edit >> Configure >> Worksheet, and check the box labeled "Use centered dot character for multiplication" and try it again?

No. 5, wrong display of approximate equal sign: looks like the font lacks that symbol. Can you switch to another font and try again?

Hope this helps,

Robert

**Comment by idealkindom** [comment] 2024-08-26 03:55
> @idealkindom Thanks for the additional example. I have downloaded Diaohuan-GB 50010-2010.zip and opened the wxmx document in it. I think that the problems you are encountering are mostly not bugs in wxMaxima.
> 
> No. 1, subscript display problem: that is a bug, and I have submitted a bug fix as you know.
> 
> No. 2, loss of square number: the problem is that the font does not have the superscript 2 sign, it appears. Can you switch to another font and try it again?
> 
> No. 3, nonsense " ": I don't see extra quote marks; can you point out exactly where the extraneous quote marks are appearing?
> 
> No. 4, wrong display of centered dot: I see that multiplication is displayed as an asterisk instead of a centered dot. Can you go to Edit >> Configure >> Worksheet, and check the box labeled "Use centered dot character for multiplication" and try it again?
> 
> No. 5, wrong display of approximate equal sign: looks like the font lacks that symbol. Can you switch to another font and try again?
> 
> Hope this helps,
> 
> Robert

Hey, Robert, thks for your patience to review the file.


No. 2, loss of square number: I tried again by switch the font to some others, which turned out to some strange display effects, thus reporting more bugs for wxMaxima? I attched the screenshots.

No. 3, nonsense " ":the extra quotation marks could be viewed clearly the word file, which I attached agin for the convenience.

No. 4, wrong display of centered dot: Of course I checkd the box labeled "Use centered dot character for multiplication", I tried agin and the results, you know, remain the same like before.

No. 5, wrong display of approximate equal sign: I tried several fonts, with no success until now. Since some font switch causes serious display of the code block, I quit testing to test the results, either.

I rely on Maxima for nearly 10 years and evertime new version comes out I tried. To my viewpoint, the version of 19.05.7 is much more stable than the latter new version despite of new functions and interfaces provided by the newer updates.
<img width="960" alt="Fig 1-switch default font to Euclid Math" src="https://github.com/user-attachments/assets/b653c4d4-a784-435d-8e5f-6c247ecb2d29">
<img width="959" alt="Fig 2-switch default font to Arial Unicode" src="https://github.com/user-attachments/assets/083019e4-d24c-4fe0-ad34-897eb6c7aa9f">
<img width="960" alt="Fig 3-switch default font to Cambria Math" src="https://github.com/user-attachments/assets/1aeb4239-7264-4348-a2a3-70f6259f43dd">
[Uploading Problem on Copying results to word.docx…]()

**Comment by robert-dodier** [comment] 2024-08-28 21:00
I looked at the .docx file and now I see what you mean by unneeded quote marks. Something to check -- see what the value of `stringdisp` is. In order to suppress quote marks, it's necessary to say `stringdisp: false`.

About the different display problems, I can't reproduce the errors. I am working with wxMaxima 24.08.0 + Maxima 5.47.0 + Windows 10. I opened your document `Diaohuan-GB 50010-2010.wxmx` and made one change, to insert `ratprint: false` to reduce the verbosity of output messages but otherwise not changing the output, and then clicked "Remove All Output" and then "Evaluate All Cells". 

I looked at the configuration settings and I see the font is set to "Segoe UI".

The output looks good to me. I don't see the unneeded quotes; the superscript 2 is visible; the approximate equal sign is correct; multiplication sign is centered dot as expected. (I do see the `sigma_s[5]` subscript problem but as you know already we are working on a bug fix for that.) 

Please see the attached screenshot: 
![wxmaxima-display-example-diaohuan](https://github.com/user-attachments/assets/e88870ec-acdf-4172-ba71-cef69e16e99e)

**Comment by idealkindom** [comment] 2024-08-29 07:02
Hey, Robert, thks a lot for informing me of the good use of "ratprint: false" to suppress the annoying strings.

I tried to transfer the font to Segoe UI, but found unsatifactory results.

1. For the results in wxMaxima, the "approx" is still a big squre. BTW, among the last part of the results like"1φ16Q235B" that "φ" is also different from that rendered by wxMaxima 19.05.7, which is rendered as a small Φ, where the vertical line crosses through.
2. As for the paste to the word, the dissapeared "approx" floated up. However the square numbers are still absent.

I attached the screenshots of results for reference.

I work also on Win 10 X64 with Maxima 5.47+ wxMaxima 24.08.0. So this may at least prove that wxMaxima 24.08.0 is dependant on much system variables, thus making ununified using experience from users to users from PCs to PCs, which is hard to imagine since Maxima setup file become much larger these years while the experience is not consistent. I seldom got in trouble with wxMaxima before Maxima 5.43.2 with wxMaxima 19.05.7.

**Comment by idealkindom** [comment] 2024-08-29 07:03
> I looked at the .docx file and now I see what you mean by unneeded quote marks. Something to check -- see what the value of `stringdisp` is. In order to suppress quote marks, it's necessary to say `stringdisp: false`.
> 
> About the different display problems, I can't reproduce the errors. I am working with wxMaxima 24.08.0 + Maxima 5.47.0 + Windows 10. I opened your document `Diaohuan-GB 50010-2010.wxmx` and made one change, to insert `ratprint: false` to reduce the verbosity of output messages but otherwise not changing the output, and then clicked "Remove All Output" and then "Evaluate All Cells".
> 
> I looked at the configuration settings and I see the font is set to "Segoe UI".
> 
> The output looks good to me. I don't see the unneeded quotes; the superscript 2 is visible; the approximate equal sign is correct; multiplication sign is centered dot as expected. (I do see the `sigma_s[5]` subscript problem but as you know already we are working on a bug fix for that.)
> 
> Please see the attached screenshot: ![wxmaxima-display-example-diaohuan](https://private-user-images.githubusercontent.com/1489136/362450930-e88870ec-acdf-4172-ba71-cef69e16e99e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTM5NTIsIm5iZiI6MTcyNDkxMzY1MiwicGF0aCI6Ii8xNDg5MTM2LzM2MjQ1MDkzMC1lODg4NzBlYy1hY2RmLTQxNzItYmE3MS1jZWY2OWUxNmU5OWUuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDY0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI4MDJkODU1ZGM3MmVkYTJiMDgwNjQ5NzNhZGE5YTU3YzMzZDk0MzVmZGM0MjE3YjFhMmU0YjVjN2QxYzRlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EpO1Y0Ocv42PSC7o8VzZu8XAWeNaz6Q9YlTKvaK43HU)

Hey, Robert, thks a lot for informing me of the good use of "ratprint: false" to suppress the annoying strings.

I tried to transfer the font to Segoe UI, but found unsatifactory results.

1.    For the results in wxMaxima, the "approx" is still a big squre. BTW, among the last part of the results like"1φ16Q235B" that "φ" is also different from that rendered by wxMaxima 19.05.7, which is rendered as a small Φ, where the vertical line crosses through.
2.  As for the paste to the word, the dissapeared "approx" floated up. However the square numbers are still absent.

I attached the screenshots of results for reference.

I work also on Win 10 X64 with Maxima 5.47+ wxMaxima 24.08.0. So this may at least prove that wxMaxima 24.08.0 is dependant on much system variables, thus making ununified using experience from users to users from PCs to PCs, which is hard to imagine since Maxima setup file become much larger these years while the experience is not consistent. I seldom got in trouble with wxMaxima before Maxima 5.43.2 with wxMaxima 19.05.7.
<img width="960" alt="wxMaxima results transfering font to Segoe UI" src="https://github.com/user-attachments/assets/191f1619-450b-4a1b-9389-e17bfdb18631">
<img width="577" alt="word paste results transfering font to Segoe UI" src="https://github.com/user-attachments/assets/376f3756-bfc2-4162-84ca-796e631046da">

**Comment by idealkindom** [comment] 2024-08-29 08:26
> I looked at the .docx file and now I see what you mean by unneeded quote marks. Something to check -- see what the value of `stringdisp` is. In order to suppress quote marks, it's necessary to say `stringdisp: false`.
> 
> About the different display problems, I can't reproduce the errors. I am working with wxMaxima 24.08.0 + Maxima 5.47.0 + Windows 10. I opened your document `Diaohuan-GB 50010-2010.wxmx` and made one change, to insert `ratprint: false` to reduce the verbosity of output messages but otherwise not changing the output, and then clicked "Remove All Output" and then "Evaluate All Cells".
> 
> I looked at the configuration settings and I see the font is set to "Segoe UI".
> 
> The output looks good to me. I don't see the unneeded quotes; the superscript 2 is visible; the approximate equal sign is correct; multiplication sign is centered dot as expected. (I do see the `sigma_s[5]` subscript problem but as you know already we are working on a bug fix for that.)
> 
> Please see the attached screenshot: ![wxmaxima-display-example-diaohuan](https://private-user-images.githubusercontent.com/1489136/362450930-e88870ec-acdf-4172-ba71-cef69e16e99e.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MTM5NTIsIm5iZiI6MTcyNDkxMzY1MiwicGF0aCI6Ii8xNDg5MTM2LzM2MjQ1MDkzMC1lODg4NzBlYy1hY2RmLTQxNzItYmE3MS1jZWY2OWUxNmU5OWUuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjlUMDY0MDUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI4MDJkODU1ZGM3MmVkYTJiMDgwNjQ5NzNhZGE5YTU3YzMzZDk0MzVmZGM0MjE3YjFhMmU0YjVjN2QxYzRlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EpO1Y0Ocv42PSC7o8VzZu8XAWeNaz6Q9YlTKvaK43HU)

I also tried to trans-use Maxima.bat between these two verision of wxMaxima for fun many times before and just now, but the results remain the same. So  I think it only relates to wxMaxima, instead of Maxima.

**Comment by robert-dodier** [comment] 2024-08-31 17:34
I see the problem with the combined superscript and subscript (e.g. `ds[3]^2`) and opened #1945 about that.

I see the problem about the quote marks and opened #1946 about that.

I don't see the problem with the centered dot turning into asterisk for multiplication. How are you copying the equations from wxMaxima to Word? There are several options and I want to make sure I am trying the same option as you.

There aren't any approximately equal signs in the text you copied, so there isn't anything to see there. I don't see any approximately equal signs in the wxmx notebook attached to this message. In order to further investigate, can you please make a very small wxmx containing only one equation with approximately equal, and then show how that's copied into Word, and attach those two files to a new bug report.

**Comment by idealkindom** [comment] 2024-09-01 02:28
> I see the problem with the combined superscript and subscript (e.g. `ds[3]^2`) and opened #1945 about that.
> 
> I see the problem about the quote marks and opened #1946 about that.
> 
> I don't see the problem with the centered dot turning into asterisk for multiplication. How are you copying the equations from wxMaxima to Word? There are several options and I want to make sure I am trying the same option as you.
> 
> There aren't any approximately equal signs in the text you copied, so there isn't anything to see there. I don't see any approximately equal signs in the wxmx notebook attached to this message. In order to further investigate, can you please make a very small wxmx containing only one equation with approximately equal, and then show how that's copied into Word, and attach those two files to a new bug report.

Hey Robert, in order to make it clear I added some remarks as comment in the original code to show the possible dignostic loacations.
Also I attached all the detailed screenshots with some necessary marks for attenstion of the full operation.
<img width="960" alt="1-wxMaxima vesion   centered dot mult checked" src="https://github.com/user-attachments/assets/c4b9ae78-89b0-4eaa-be36-32130fbd681e">
<img width="486" alt="2-Segoe UI font Choosen" src="https://github.com/user-attachments/assets/06d5c71c-1421-4e69-9ec0-ae3960f5d716">
<img width="945" alt="3-Results concerning approc missing" src="https://github.com/user-attachments/assets/6b830702-6a57-4c87-85ff-c27dae3ed1dd">
<img width="960" alt="4-Copy process" src="https://github.com/user-attachments/assets/11baceb5-ccae-445d-b1b7-f7d48aca23ec">
<img width="959" alt="5-word 2016 paste operation and option" src="https://github.com/user-attachments/assets/f3ecb6f4-3eec-483c-bf7c-8c1f03cd4821">
[Diaohuan-GB 50010-2010.zip](https://github.com/user-attachments/files/16827057/Diaohuan-GB.50010-2010.zip)
<img width="955" alt="6-word paste results" src="https://github.com/user-attachments/assets/39e163e3-2cef-48fc-9a08-39526168b19a">

**Comment by robert-dodier** [comment] 2024-09-02 04:24
Both problems (approximately equal sign replaced by empty square, and substitution of asterisk for centered dot in copied text) are caused by the wrong font being selected.

As you showed above, you selected Segoe UI for "Code Default (Maxima input)". However, you can see that the output __is not__ Segoe UI, because Segoe UI is a sans serif font while the actual output is a serif font (i.e., serif font has the little "feet" on the ends of letters, and sans serif does not have the little feet). Looks like your output font is Times New Roman. 

__You must select a different font for "Math Default".__ Try that and post an update here to say how it turns out.

**Comment by idealkindom** [comment] 2024-09-02 06:09
> Both problems (approximately equal sign replaced by empty square, and substitution of asterisk for centered dot in copied text) are caused by the wrong font being selected.
> 
> As you showed above, you selected Segoe UI for "Code Default (Maxima input)". However, you can see that the output **is not** Segoe UI, because Segoe UI is a sans serif font while the actual output is a serif font (i.e., serif font has the little "feet" on the ends of letters, and sans serif does not have the little feet). Looks like your output font is Times New Roman.
> 
> **You must select a different font for "Math Default".** Try that and post an update here to say how it turns out.

Hey, Robert. I tried to find maybe I should accept the fact that Segoe UI font to be checked is the best way to avoid rendering bug. Because other fonts may inccurr strange  and sometimes radiculous outcomes.
Here I attached some test process and results' screenshot if you are interested.
<img width="945" alt="Results with 20240901 nightly built Maxima" src="https://github.com/user-attachments/assets/37f98914-1f62-4e36-97e8-4b846a926d6b">
<img width="950" alt="Results with Ascii math font set to Cambria Math" src="https://github.com/user-attachments/assets/5ffc95b0-e7d6-4293-8538-8c7796b9338b">
<img width="945" alt="Results with Default math font set to Segoe UI" src="https://github.com/user-attachments/assets/6905e289-3c6d-44c7-9306-640c0519b10b">
<img width="945" alt="Results with defaut math font set to Cambria Math" src="https://github.com/user-attachments/assets/3a08af89-64ab-4a86-8c39-e404e6b5f717">
<img width="960" alt="Set Ascii math font to be Cambria Math" src="https://github.com/user-attachments/assets/331a4bea-6fac-495a-b898-d3cf512c811f">
<img width="486" alt="set Default math font set to Segoe UI" src="https://github.com/user-attachments/assets/4f366368-1e3a-4ad9-8fce-afab071991e4">
<img width="486" alt="Set Default math font to Cambria Math" src="https://github.com/user-attachments/assets/ff49cfbe-61b5-4464-829d-eec13dd86659">

BTW, at last I installed the nightly built Maxima with the lates wxMaxima merged your fix of subscript bug, and I found in the setting console  the fonts are generally pre-defined to be Segoe UI, alright. 

Thanks a lot Robert for terminating the Marathon bug of subscripts hindering me from using latest wxMaxima as daily production gear.

**Comment by idealkindom** [comment] 2024-09-02 06:11
> Both problems (approximately equal sign replaced by empty square, and substitution of asterisk for centered dot in copied text) are caused by the wrong font being selected.
> 
> As you showed above, you selected Segoe UI for "Code Default (Maxima input)". However, you can see that the output **is not** Segoe UI, because Segoe UI is a sans serif font while the actual output is a serif font (i.e., serif font has the little "feet" on the ends of letters, and sans serif does not have the little feet). Looks like your output font is Times New Roman.
> 
> **You must select a different font for "Math Default".** Try that and post an update here to say how it turns out.

BTW, I set the background to be light green. Latest wxMaxima you see the herizontal lines like table, it appears when you scroll the working window, but disspears a while after you stop the scroll, a little bit ugly.

**Comment by idealkindom** [comment] 2024-09-02 06:25
> Both problems (approximately equal sign replaced by empty square, and substitution of asterisk for centered dot in copied text) are caused by the wrong font being selected.
> 
> As you showed above, you selected Segoe UI for "Code Default (Maxima input)". However, you can see that the output **is not** Segoe UI, because Segoe UI is a sans serif font while the actual output is a serif font (i.e., serif font has the little "feet" on the ends of letters, and sans serif does not have the little feet). Looks like your output font is Times New Roman.
> 
> **You must select a different font for "Math Default".** Try that and post an update here to say how it turns out.

Sorry, Forget to say, the centered-dot multiplication operator is still pasted as asterisk in word.
Find the attached screenshots.
<img width="952" alt="Resuls with All in Segoe UI font" src="https://github.com/user-attachments/assets/b6391bbb-4dfe-44d7-bae6-f4c8a5f3ef24">
<img width="960" alt="centered-dot operator copy and paste to word" src="https://github.com/user-attachments/assets/fe599140-b8b9-4043-bc83-51fedbb89f94">

**Comment by robert-dodier** [comment] 2024-09-02 19:33
About the asterisk problem, I still can't reproduce it. Can you please output all the settings via Edit >> Configure >> Revert all to defaults >> Export all settings, and then attach that to this bug report.

I'm sorry for the bother, but it would probably help if you would try to copy and paste the multiplication expression again to verify that the problem exists in the same session when you export the settings.

**Comment by idealkindom** [comment] 2024-09-03 06:12
> About the asterisk problem, I still can't reproduce it. Can you please output all the settings via Edit >> Configure >> Revert all to defaults >> Export all settings, and then attach that to this bug report.
> 
> I'm sorry for the bother, but it would probably help if you would try to copy and paste the multiplication expression again to verify that the problem exists in the same session when you export the settings.

Hey，Robert，Never say sorry for that. It's me bothering you for all these problems.
I tried before revert all settings to default to test it again, the asterisk still persist for sure.
I export the full setting and style setting,though the console panel has two options for export I found they may be the same, same default file name and size. Anyway, I did both of them with respective name(the second received default name by wxMaxima itself).
<img width="486" alt="Export screenshot" src="https://github.com/user-attachments/assets/f7d9bbf8-1533-410a-922b-0b1095516d5e">
Later I revert all settings to default and test it again, nothing changed for asterisk though.
I attched all the setting files in a zip here. Hope you could diagnose the problem and help to fix the annoying problem.
[wxMaxima problem 20240903.zip](https://github.com/user-attachments/files/16844284/wxMaxima.problem.20240903.zip)

**Comment by robert-dodier** [comment] 2024-09-25 00:35
I'm closing this ticket because the several items mentioned here are all covered by other tickets.

(1) subscript display problem: Fixed; see #1807.
(2) superscript combined with subscript goes missing in copied output. Fixed; see #1945.
(3) spurious quote marks in copied output. Fixed; see #1946.
(4) centered dot copied as asterisk. Fixed; see #1956.
(5) approximately-equal sign appears as empty square. Open; see #1958.

If there are additional issues, *please open a new ticket for each separate issue*. Let's not combine different topics into the same ticket. Thanks to everybody for working on this stuff, I think we're making a lot of progress.

**Closed by robert-dodier** 2024-09-25 00:35 UTC
