### ISSUE TITLE
build error on Manjaro: missing wxmaxima.zh_CN.md

### ISSUE THREAD

**Issue by IInatas** [wxMaxima-developers/wxmaxima#1917] opened 2024-05-13 06:56 UTC
hi all together

will updating in Manjaro it tried to update to version wxmaxima 24.05.0-1 (Mo 13 Mai 2024 07:57:41 CEST), but the process failed.
The system contains the following tools:
-- Found pandoc: /usr/bin/pandoc (found version "3.1.8")
-- Found LATEX: /usr/bin/latex  found components: XELATEX LUALATEX 
-- Found Gettext: /usr/bin/msgmerge (found version "0.22.4")
-- Found Maxima: /usr/bin/maxima (found version "5.47.0")
-- Found appstreamcli: /usr/bin/appstreamcli (found version "1.0.2")

the unpacking was smooth and the compile run is starting just fine, but after 9%
....
[ 10%] Embedding toleranceCalculations.wxm
[ 10%] Built target build_toleranceCalculations.h
[ 11%] Generating wxmaxima.zh_CN.html
pandoc: wxmaxima.zh_CN.md: withBinaryFile: does not exist (No such file or directory)
make[2]: *** [info/CMakeFiles/build_wxmaxima.zh_CN.html.dir/build.make:73: info/wxmaxima.zh_CN.html] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1376: info/CMakeFiles/build_wxmaxima.zh_CN.html.dir/all] Fehler 2
make[1]: *** Waiting for unfinished processes …
[ 11%] Built target build_manualanchors.h
make: *** [Makefile:166: all] Error 2

So far it looks like the file wxmaxima.zh_CN.md is missing. The file wxmaxima.zh_CN.html is present, so may be the is no need to build it from the md file?

I would like to receive instructions on how to proceed in order to perform a successful build run.  

regards,
Marcus

**Comment by daute** [comment] 2024-05-13 13:10
Please install po4a too. (https://packages.manjaro.org/?query=po4a). The language specific Markdown files are generated using po4a.
Best regards, Wolfgang

**Comment by daute** [comment] 2024-05-13 20:29
Hm. I tried to 'fix' the issue when po4a is not installed now, but it works properly.
If it is installed you should get a message like
```
-- Found po4a: /usr/bin/po4a (found version "0.57")
```
(0.57 is rather old, yes), or:
```
-- po4a not found. Disable the generation of localized documentation.
```

What do you get? Here the build works in both cases. Can you post the complete output of the cmake configuration run for wxMaxima (when using an empty build directory?)
Best regards, Wolfgang

**Comment by IInatas** [comment] 2024-05-14 06:08
Dear Wolfgang

thank you for looking into my issue.
I updated po4a and tried again to compile wxmaxima and it failed again.
Please find below my log:


regards,
Marcus


Erstelle wxmaxima...
==> Erstelle Paket: wxmaxima 24.05.0-1 (Di 14 Mai 2024 07:47:30 CEST)
==> Prüfe Laufzeit-Abhängigkeiten...
==> Prüfe Buildtime-Abhängigkeiten...
==> Empfange Quellen...
  -> wxmaxima-24.05.0 gefunden
  -> wxmaxima-24.05.0.asc gefunden
==> Überprüfe source Dateien mit sha512sums...
    wxmaxima-24.05.0 ... Erfolg
    wxmaxima-24.05.0.asc ... Übersprungen
==> Überprüfe Signaturen der Quell-Dateien mit gpg...
    wxmaxima-24.05.0 ... Erfolg
==> Entferne existierendes $srcdir/ Verzeichnis...
==> Entpacke Quellen...
  -> Entpacke wxmaxima-24.05.0 mit bsdtar
==> Entferne existierendes $pkgdir/ Verzeichnis...
==> Beginne build()...
-- The CXX compiler identification is GNU 13.2.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake version:                      3.29.2
-- CMake config:                       
-- wxWidgets config:                   
-- Looking for wxWidgets in:           
-- Looking for wxWidgets libraries in: 
-- Found wxWidgets: -pthread;-lwx_gtk3u_richtext-3.2;-lwx_gtk3u_aui-
3.2;-lwx_gtk3u_webview-3.2;-lwx_baseu_net-3.2;-lwx_gtk3u_qa-3.2;-
lwx_gtk3u_html-3.2;-lwx_baseu_xml-3.2;-lwx_gtk3u_core-3.2;-lwx_baseu-
3.2 (found suitable version "3.2.4", minimum required is "3")
-- Found wxWidgets: (found version "3.2.4")
-- Found Git: /usr/bin/git (found version "2.45.0")
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- rpmbuild not found - no RPM package will be build with make package.
-- Found Doxygen: /usr/bin/doxygen (found version "1.10.0") found
components: doxygen dot
-- You can create a Doxygen documentation of the source code with:
cmake --build . -- Doxygen
-- Found po4a: /usr/bin/vendor_perl/po4a (found version "0.71")
/var/tmp/pamac-build-marcus/wxmaxima/src/build/po4a.cfg:1: Directory
'../wxmaxima-Version-24.05.0/locales/manual' not found in
'/var/tmp/pamac-build-marcus/wxmaxima/src'.
-- Calling po4a with the option --no-update - not updating the po/pot
files in the source tree.
-- Remark: older versions of po4a seem to update the pot file, although
the option --no-update is used.
-- Found pandoc: /usr/bin/pandoc (found version "3.1.8")
-- Found LATEX: /usr/bin/latex  found components: XELATEX LUALATEX
-- Found Gettext: /usr/bin/msgmerge (found version "0.22.4")
-- The updated POT and PO files were generated in the build directory.
-- Call 'make update-locale' to update the .po files in the source
tree, too.
-- Embedding following files into header file /var/tmp/pamac-build-
marcus/wxmaxima/src/build/wxm_statusbar_images.h
--    Processing: network-idle.svg.gz
--    Processing: Dialog-accept.svg.gz
--    Processing: network-offline.svg.gz
--    Processing: Emblem-equal-defined.svg.gz
--    Processing: network-receive.svg.gz
--    Processing: Emblem-important.svg.gz
--    Processing: network-transmit-receive.svg.gz
--    Processing: Go-previous.svg.gz
--    Processing: network-transmit.svg.gz
--    Processing: Go-up.svg.gz
--    Processing: System-lock-screen.svg.gz
--    Processing: network-error.svg.gz
--    Processing: Waiting.svg.gz
-- Embedding following files into header file /var/tmp/pamac-build-
marcus/wxmaxima/src/build/wxm_config_images.h
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/document-export.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/edit-copy-confdialogue.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/edit-copy_backup.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/editing.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/maxima.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/options.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/styles.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/config/view-refresh.svg.gz
-- Embedding following files into header file /var/tmp/pamac-build-
marcus/wxmaxima/src/build/wxm_draw_images.h
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_ContourBase.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_ContourBoth.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_ContourMap.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_ContourNone.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_ContourSurface.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_Explicit.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_Implicit.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/draw/Draw_Parametric.svg.gz
-- Embedding following files into header file /var/tmp/pamac-build-
marcus/wxmaxima/src/build/wxm_toolbar_images.h
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/arrow-up-square.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/dialog-information.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/edit-copy.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/edit-cut.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/edit-find.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/eye-slash.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/go-bottom.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/go-jump.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/go-last.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/go-next.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-copy.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-cut.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-find.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-help.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-new.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-open.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-paste.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-preferences.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-print.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-redo.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-save.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-select-all.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-stop.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/gtk-undo.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/input.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/media-playback-stop.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/software-update-urgent.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/text.svg.gz
--    Processing: /var/tmp/pamac-build-marcus/wxmaxima/src/wxmaxima-
Version-24.05.0/art/toolbar/view-refresh1.svg.gz
-- Found Maxima: /usr/bin/maxima (found version "5.47.0")
-- Found appstreamcli: /usr/bin/appstreamcli (found version "1.0.3")
-- Configuring done (1.7s)
-- Generating done (0.0s)
-- Build files have been written to: /var/tmp/pamac-build-
marcus/wxmaxima/src/build
[  0%] Embedding variableNames.wxm
[  0%] Generating our private copy of nanosvg.h
[  0%] Built target build_nanosvg_private.h
[  0%] Built target build_variableNames.h
[  1%] Generating our private copy of nanosvgrast.h
[  1%] Embedding the example worksheet for the config dialogue
[  1%] Built target build_nanosvgrast_private.h
[  2%] Embedding wxMathML.lisp
[  2%] Built target build_sampleWorksheet.h
[  2%] Embedding NEWS.md
[  2%] Built target build_news_md.h
[  2%] Embedding the license information
[  2%] Built target build_license.h
[  3%] Embedding the anchors of the maxima manual
[  3%] Built target build_wxMathML.h
[  4%] Embedding builtin_commands.txt
[  4%] Built target build_builtin_commands.h
[  4%] Embedding sumSign.svg
[  4%] Built target build_sumSign.h
[  4%] Embedding prodSign.svg
[  4%] Built target build_prodSign.h
[  5%] Embedding intSign.svg
[  5%] Built target build_intSign.h
[  5%] Embedding CASvsProgrammingLanguage.wxm
[  5%] Built target build_CASvsProgrammingLanguage.h
[  5%] Embedding diffEquations.wxm
[  5%] Built target build_diffEquations.h
[  6%] Embedding displaying3DCurves.wxm
[  6%] Built target build_displaying3DCurves.h
[  6%] Embedding fastListAccess.wxm
[  6%] Built target build_fastListAccess.h
[  6%] Embedding fittingEquations.wxm
[  6%] Built target build_fittingEquations.h
[  6%] Embedding memoizing.wxm
[  6%] Built target build_memoizing.h
[  8%] Embedding numberFormats.wxm
[  8%] Built target build_numberFormats.h
[  9%] Embedding solvingEquations.wxm
[  9%] Built target build_solvingEquations.h
[ 10%] Embedding toleranceCalculations.wxm
[ 10%] Built target build_toleranceCalculations.h
[ 11%] Generating wxmaxima.zh_CN.html
pandoc: wxmaxima.zh_CN.md: withBinaryFile: does not exist (No such file
or directory)
make[2]: ***
[info/CMakeFiles/build_wxmaxima.zh_CN.html.dir/build.make:73:
info/wxmaxima.zh_CN.html] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:1376:
info/CMakeFiles/build_wxmaxima.zh_CN.html.dir/all] Fehler 2
make[1]: *** Es wird auf noch nicht beendete Prozesse gewartet …
[ 11%] Built target build_manualanchors.h
make: *** [Makefile:166: all] Fehler 2
==> FEHLER: Ein Fehler geschah in build().
    Breche ab...





Am Montag, dem 13.05.2024 um 13:29 -0700 schrieb Wolfgang Dautermann:

**Comment by daute** [comment] 2024-05-14 19:59
I tried to reproduce it, you use the parameter `-B build-dir` of CMake, correct? The may be the reason of the issue, please do - for now - execute:
```
cd <build-dir>
cmake <path-to-source-dir>
make
```
instead to build wxMaxima (and solve the problem fast). But you found a problem, I will check it in the near future how to solve it correct (commit c975ead7d68bce1ab3d0071408b523c3f659acee seems to be problematic in this case).

**Comment by daute** [comment] 2024-05-15 19:33
I assume, with commit 71ef86fd65f10771ea7c069757ee6d879edaf671 your problem is solved. Is it?

**Comment by daute** [comment] 2024-05-19 06:45
No feedback from [IInatas](https://github.com/IInatas), but closing the ticket, as I am pretty sure, that I fixed it.

**Closed by daute** 2024-05-19 06:45 UTC
