### ISSUE TITLE
Detect if the lisp supports Unicode and "tweak" behavior based on that

### ISSUE THREAD

**Issue by KubaO** [wxMaxima-developers/wxmaxima#1336] opened 2020-07-10 20:00 UTC
This would improve user experience. 

- [ ] Detect Unicode support - write a temporary file in wxMaxima that contains characters from various code pages, attempt to open it in `wxmathml.lisp`, and report the success/failure back

With no Unicode support:

- [ ] Unix: Create symbolic links in temp folder to directories and files that contain unsupported characters, and pass those links to Maxima
- [ ] Windows with non-administrator symlink support: Do as on Unix
- [ ] Windows without symlink support: Ugh. We can create a temporary working directory in temp folder, and maybe override the lisp I/O functions to translate file names on the fly by copying files to temporary files? No idea what's needed here to make it work reasonably.

The idea is not to go overboard: do what resolves typical problems that kill user experience, and no more.

**Comment by gunterkoenigsmann** [comment] 2020-07-11 01:36
There are variou degrees of Unicode support:

  * gcl is encoding-agnostic, which means: It doesn't support unicode - but if it encounters unicode it does the Right Thing
  * #674 is caused by the fact that SBCL fully supports unicode with the exception that if the directory name contains non-ascii chars, but the path to a file is encoded in some weird codepage it cannot open that file, while it knows how to handle the filename itself if the filename contains unicode.

**Comment by KubaO** [comment] 2020-07-11 03:31
A workaround on Windows: provide a FFI C api that could be used from wxmath.lisp to implement needed replacements for the lisp low level file I/O, that would not suffer from
this “malaise”. Export the api symbols directly from the exe file (you may not know, but exe files are a superset of dll files: you can dynamically link to multiple exe files just as you can to dll files - and that works for elf binaries too!). Thus we won’t need to deal with extra files: wxmath.lisp would be told the location of wxMaxima executable and it would use the FFI in lisp to dynamically link to wxMaxima. That could also be used to implement a much faster data exchange scheme since both sides of the connection would reside within the same binary, and be compatible by default. I’ve done such trick with Forth on the other end of the connection (in place of Lisp) and it worked quite well.

**Comment by gunterkoenigsmann** [comment] 2020-07-11 08:28
That would mean to trust complicated things like Fri in a world in which simple Unicode won't work. 

SBCL makes new releases roughly monthly and the SBCL maintainers are quite helpful. Perhaps it would suffice to tell them we have this problem in a way they understand. My last try to do so wasn't too successful, mainly because I don't know how to set up a system that uses non-ascii non-unicode characters in a path name while SBCL uses Unicode. the other problem would be that none of the devs seems to own a windows computer...

**Comment by gunterkoenigsmann** [comment] 2020-07-15 06:52
The question is if unicode handling is still a problem, nowadays: Maxima gives different results for different variable names, somedays. But the problem isn't unicode handling. Instead it always is the dependence of some algorithm on the alphabetic search order of variable names.

...and sbcl poorly handles non-ascii non-unicode pathnames. But that's an altogether different problem.

**Comment by KubaO** [comment] 2020-07-15 14:54
I’m not opposed to closing this then. If someone finds problems, they can submit a new issue, as always. We’re on some sort of reasonable trajectory to have all outstanding bug issues closed in maybe two months from now. That doesn’t mean there won’t be bugs of course, but it does mean that there are more bug fighters around.

**Comment by gunterkoenigsmann** [comment] 2020-07-16 05:27
When Andrejv still was the maintainer of wxMaxima he was very patient even if the original bug report was rather offensive (often bug reporters that drastically complained without giving any real information, if taken seriously, turned out to be excellent testers). Also he was opposed to closing tickets just because the maintainers thought it was invalid/not solvable within wxMaxima/ was breaking more workflows than it helps with or if the maintainers believed that it was likely to be solved already, but were not sure about that. Sometimes bugs that clearly are fixed on the developer's machine have still pendants the user still triggers. And many tickets I immediately would have discarded one or two years later after enough of wxMaxima has changed would turn out to be interesting additions.

The disadvantage of this approach is that it is still easy to get lost in a pile of bug tickets that are resolved or are likely to be wontfix ones. I think it might be the Right Time to clean up now ;-)

**Closed by gunterkoenigsmann** 2020-07-16 05:27 UTC
Labels: feature request

**Comment by KubaO** [comment] 2020-07-16 13:47
My mindset is similar, and I have looked over lots of closed issues as well to see if they may not have resurfaced. I think I fixed a bug in the ~500 range too :) But some reports are so vague and the reporters provide no feedback so we can’t really do much and I don’t worry about getting these closed. There are some long-standing architectural issues we have, so several classes of bugs are indicative of that, and some issues may just stay around.
