### ISSUE TITLE
Bug with blank spaces

### ISSUE THREAD

**Issue by SengerM** [wxMaxima-developers/wxmaxima#1031] opened 2018-09-20 02:09 UTC
Hello,
I have made a question in the discussion forum, but making some tests I think I have found a bug. I am sorry if it is not. I am having a very strange behavior with blank spaces. The image in [this link](https://image.ibb.co/fwkuWe/imagen.png) illustrates the problem I am having. Before the definition of 'C' it seems that the "number 0" is being interpreted as "the variable 0". This happens for other numbers as well, as can be seen in [this link](https://image.ibb.co/inkYPz/imagen.png). I had also problems with symbols having the same name but being considered as different by wxMaxima.

I am running wxMaxima 18.02.0 ([this version](https://image.ibb.co/jh6RSK/imagen.png)) in Xubuntu 18.04.

If I execute a script in maxima from terminal containing this:

	A: 1=1;
	B: 2=2;
	C:3=3;
	D: 4=4;

	A^2;
	B^2;
	C^2;
	D^2;

everything works as expected.

**Comment by gunterkoenigsmann** [comment] 2018-09-20 04:17
Does the issue disappear if you only press the space bar without pressing shift? 

Shift+Space is interpreted as a non-breakable space. Not that I have introduced a big here...

**Comment by SengerM** [comment] 2018-09-20 11:00
I didn't knew about Shift+Space. I have introduced all the spaces just as ordinary ones. I have made a test using Shift+Space and [this](https://image.ibb.co/bPtAMe/imagen.png) is what I get.

**Comment by gunterkoenigsmann** [comment] 2018-09-21 05:32
As I cannot reproduce the bug on my computer: Does it still appear if you use the maxima + wxMaxima version from here: https://code.launchpad.net/~maxima-developers/+archive/ubuntu/maxima-nightly

It might be necessary to uninstall maxima+wxMaxima before installing the nightly build.

My guess is that the bug might already have been fixed, perhaps accidentally as I don't remember ever having read about it.

Thanks a lot,
Gunter.

**Comment by leon-vv** [comment] 2018-09-22 11:50
I can confirm that this bug is currently in Debian Testing but is not present anymore in the nightly build.

**Comment by SengerM** [comment] 2018-09-22 19:16
I have installed that version and it seems the problem is gone. I'll keep on testing and if something happens I'll let you know.

Thanks!

**Comment by gunterkoenigsmann** [comment] 2018-09-22 20:43
We urgently need a new Maxima+wxMaxima release.

**Comment by jlindgren90** [comment] 2019-04-23 15:02
Shift+Space still does something different than Space for me, using wxMaxima 19.04.3-27~201 from the maxima-nightly PPA.  I have not updated maxima itself due to a file conflict between maxima and maxima-common.

**Comment by jlindgren90** [comment] 2019-04-23 15:25
wxmaxima 15.08.2 (from the Ubuntu 16.04 repository) still works correctly, but you have to also downgrade maxima to the xenial version.

**Comment by robert-dodier** [comment] 2019-08-12 03:08
Hi @gunterkoenigsmann, is the behavior of Shift+Space the same as before or has it been changed? If it has changed, do you know which commit changed it? Thanks for any information.

I have built wxMaxima from current source and it advertises itself as wxMaxima 19.07.0-DevelopmentSnapshot. It appears that Shift+Space is recognized as non-breaking space in strings, but not in code; in code, Shift+Space appears to be treated as ordinary space. Is that the intended behavior now? or perhaps I have misunderstood what's happening? Again, thanks for any insights.

**Comment by rknop** [comment] 2019-09-29 12:45
The way it works in 19.09 is a nightmare.  If you are holding down the shift key while you press space, on the input line it looks exactly the same as it does if you aren't holding down shift . However, wxmaxima and/or maxima interprets it as something other than a space.  So, for exmple, if you type "2 + 2" into wxmaxima, with regular spaces, you get 4 as expected.  If instead they are shift-spaces, you get the error:

<pre>
incorrect syntax:   is not an infix operator
2\302\240+
  ^
incorrect syntax: Premature termination of input at ;.
;
^
</pre>

This makes wxmaxima 19.09 completely unusable.  Typing fast, sometimes a shift-space happens after something like : or (.  When you can't see the difference on the screen, you don't know that it happened.  It's worse when you try something like "matrix( [ a ], [ b ] )", because no error is reported, and the output is only very subtly different when you have shift-spaces or regular spaces.  Yet, semantically, they aren't the same thing.

Is there a fix for this somewhere?  I can't use current versions of wxmaxima with this issue in place.

**Comment by robert-dodier** [comment] 2019-09-30 04:48
@rknop  I looked at the source code and it appears there is no way to disable Shift+Space --> nonbreaking space. I have submitted a pull request (i.e. bug fix) to remove that behavior. Until/unless that's approved, the only advice I have is either to type carefully, or to avoid spaces altogether. Both alternatives are somewhat painful, sorry for that.

**Comment by leon-vv** [comment] 2019-09-30 04:58
A temporary workaround for me was to shortcut Shift+Space to a no op in my window manager so the Shift+Space doesn't get delivered to wxMaxima

**Comment by gunterkoenigsmann** [comment] 2019-09-30 05:30
On my computer I cannot reproduce the problem. Either it already is solved in the current code or we'll have to find out what is different between our machines.

**Comment by gunterkoenigsmann** [comment] 2019-09-30 06:54
Robert finally put me on the right track: Non-breaking spaces are now replaced by ordinary spaces before sending them to maxima. The only thing I am not sure about is: Do we want to keep non-breaking spaces in strings? That would be helpful if somebody tries to make maxima generate files that contain them. But it would cause problems if someone accidentally hit the "non-breaking space" hotkey and then wants maxima to interpret a sting as an equation. Just replacing all non-breaking spaces by ordinary spaces before sending them to maxima will be in tomorrow's nightly build, of 8e9746d2b49f1b994b5050e0db029bac5c4e21ba compiles - which should be the case. For MS Windows this build can be downloaded tomorrow at https://wolfgang.dautermann.at/maxima/nightlybuild/ 
Alternately the CI we use for wxMaxima should automatically create a wxMaxima-only installer that will be downloadable at https://ci.appveyor.com/project/gunterkoenigsmann/wxmaxima/artifacts in about five minutes. If the problem still persists please complain and I will re-open this ticket.

**Closed by gunterkoenigsmann** 2019-09-30 06:54 UTC
