### ISSUE TITLE
Downloads wrong version and ??command issue

### ISSUE THREAD

**Issue by nchencinski** [wxMaxima-developers/wxmaxima#1882] opened 2024-01-12 19:13 UTC
When going to download version 23.12.0 is listed as the latest version. When downloaded I get version 23.05.1
This version has an issue with the ?? command.

(%i3)	??linsolve;
 0: fast_linsolve  (Functions and Variables for Affine)

 1: linsolve  (Functions and Variables for Equations)

 2: linsolve_params  (Functions and Variables for Equations)

 3: linsolvewarn  (Functions and Variables for Equations)Enter space-separated numbers, `all' or `none':	1;
(%o3)	true

Does not give the information on Linsolve just the status    "true"

-------------------------------------------------------------
build_info(version="5.47.0",timestamp="2023-06-02 20:31:42",host="x86_64-w64-mingw32",lisp_name="SBCL",lisp_version="2.3.2",maxima_userdir="C:/Users/nchen/maxima",maxima_tempdir="C:/Users/nchen/AppData/Local/Temp",maxima_objdir="C:/Users/nchen/maxima/binary/5_47_0/sbcl/2_3_2",maxima_frontend="wxMaxima",maxima_frontend_version="23.05.1_MSW")
-------------------------------------------------------------

Thank You
       Norbert Chencinski

**Comment by daute** [comment] 2024-01-13 07:25
Hi Norbert,
You downloaded the Windows installer from:
https://sourceforge.net/projects/maxima/files/Maxima-Windows/5.47.0-Windows/

5.47.0 is the latest Maxima version (the software, which does the mathematical computations, but it does only provide a small graphical user interface (Xmaxima)). In the Windows-installer several additional (external) components are included, e.g. wxMaxima (and Gnuplot, Lips-compilers, etc.) in the versions, which was available when the installer was build (June 2023) - and that was wxMaxima 23.05.1.
Maxima (which does the mathematics) and wxMaxima (which provides a nice graphical user interface for Maxima) are two different projects.

You can download a Windows installer for the most recent wxMaxima release (which contains only wxMaxima (the graphical user interface, you will still need a Maxima installation too) from the wxMaxima website: https://github.com/wxMaxima-developers/wxmaxima/releases

Or there are 'nightly builds' - build automatically and completely untested - of the current development version of Maxima and wxMaxima available at my website: https://wolfgang.dautermann.at/maxima/nightlybuild/

Best regards,

Wolfgang (I build the Windows-installers for Maxima and wxMaxima (crosscompiled on Linux))

**Comment by robert-dodier** [comment] 2024-08-28 21:53
I've opened a new ticket #1944 about the downloads page, which supersedes this ticket, so I'll close this one.

This ticket also mentions the unrelated issue about ??, which I can't reproduce, so I'm just going to close it.

**Closed by robert-dodier** 2024-08-28 21:53 UTC
