### ISSUE TITLE
Changing Text Cell Background color causes exported html document to be completely in that color

### ISSUE THREAD

**Issue by ejbarth** [wxMaxima-developers/wxmaxima#1562] opened 2021-07-06 15:45 UTC
Selecting a background color for text cells works in the wxMaxima window, but when that is exported to html, the resulting html document has that background color for the entire document.

wxMaxima version: 21.05.2_MSW
using wxWidgets version: wxWidgets 3.1.4
Maxima version: 5.45.1
Maxima build date: 2021-06-21 17:43:28
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\Eric Barth\maxima\
Help dir: C:\maxima-5.45.1\share/doc/wxmaxima

**Comment by daute** [comment] 2022-01-08 20:27
This is a duplicate of bug https://github.com/wxMaxima-developers/wxmaxima/issues/1434 - which was already solved by Gunter. Tried the recent release 21.11.0 (Windows) and the current development version (Linux), it does not occur there.

Closing this bug report.

**Closed by daute** 2022-01-08 20:27 UTC
