### ISSUE TITLE
'wxMaxima' on MacPorts is outdated and does not work with macOS 10.15

### ISSUE THREAD

**Issue by NiftyPan** [wxMaxima-developers/wxmaxima#1218] opened 2020-03-03 14:42 UTC
Despite the advice to install from MacPorts, I find that the wxMaxima version there is quite outdated, and that it will not work with macOS Catalina. Specifically, the window arrangements are not only bad, but I cannot see any text! Please update the port for MacPorts users to the latest reliable version.

**Comment by gunterkoenigsmann** [comment] 2020-03-03 18:16
Unfortunately I know no contact at macports that I can forward your request to package a new package for. If that is the right way of getting a package in macports updated, that is. Also not owning a mac I would not have the possibility to do any of the possibly-required testing => unfortunately in this case all I can tell you is that even if this is the most logical place to ask for this request I cannot do anything helpful. Sorry for that.

**Comment by NiftyPan** [comment] 2020-03-04 17:37
I see, I'm not sure how it could be done either. I will raise the issue with MacPorts anyway.

**Comment by gunterkoenigsmann** [comment] 2020-03-05 06:24
Cool! Thanks a lot! In the last few years much has been improved on wxMaxima so that will be a great addition to MacPorts.

**Comment by MSoegtropIMC** [comment] 2020-03-06 07:22
See also #1220 - I am working on a new MacPorts file.

But I must say that the existing one does work for me on Catalina - despite the fact that it is quite old. I have been using it daily for 10 days or so.

The windows layout is indeed broken - it can be fixed by enabling the history window. As far as I can tell the problems are produced by a bad disabled history window and enabling ti fixes it. Just a workaround until #1220 is done.

**Comment by MSoegtropIMC** [comment] 2020-03-06 07:37
@NiftyPan : did you rise a ticket at MacPorts? If so, could you link it here so that I can comment there as well?

**Comment by gunterkoenigsmann** [comment] 2020-03-12 16:58
As soon as wxMaxima has created its main window all error and debug messages appear in the debug log window instead of in stderr. I therefore have now tried to silence all commands that are executed before the main window is created. With a bit of luck that resolves the communication problems.

**Comment by KubaO** [comment] 2020-07-10 20:34
This is really a duplicate of #1220

**Closed by KubaO** 2020-07-10 20:34 UTC
