### ISSUE TITLE
Please update the snap version, it's still 17.04.1

### ISSUE THREAD

**Issue by WuShichao** [wxMaxima-developers/wxmaxima#1124] opened 2019-05-06 00:50 UTC
https://snapcraft.io/wxmaxima
I think snap version is much easier to install (auto update).

**Comment by gunterkoenigsmann** [comment] 2019-05-06 05:57
After I found out how big snap packages are and after I ran into problems with uploading things to snapcraft.io that weren't resolved within months I was convinced snaps aren't really used or supported.

Will try to upload a new snap package this evening.

**Comment by gunterkoenigsmann** [comment] 2019-05-07 06:38
Seems like Ubuntu has lost the ability to build snap packages more than a year ago. Will try to install an old Ubuntu in a virtual machine hoping that that works.

**Comment by gunterkoenigsmann** [comment] 2019-05-07 07:18
Ok... ...the problem is:

- Ubuntu versions later than xenial no more can produce snap packages
- and xenial still has the bug https://bugs.launchpad.net/snapd/+bug/1731519

=> currently there might be no way to produce new snap packages of wxMaxima.

**Comment by KubaO** [comment] 2020-07-10 16:51
Closing this since it is an issue with external framework/components that we have no control on. Can be reopened when the underlying blockers get resolved.

**Closed by KubaO** 2020-07-10 16:51 UTC
