### ISSUE TITLE
Build error on docker

### ISSUE THREAD

**Issue by gunterkoenigsmann** [wxMaxima-developers/wxmaxima#1386] opened 2020-08-29 17:29 UTC
Elias Mårtenson found this trying to build docker-wxmaxima which our ci succeeded in once:

````
[ 32%] Building CXX object src/CMakeFiles/wxmaxima.dir/AbsCell.cpp.o
In file included from /wxmaxima/src/TextStyle.h:39:0,
                 from /wxmaxima/src/Configuration.h:32,
                 from /wxmaxima/src/Cell.h:34,
                 from /wxmaxima/src/AbsCell.h:33,
                 from /wxmaxima/src/AbsCell.cpp:31:
/wxmaxima/src/FontAttribs.h:140:41: error: specialization of 'template<class _Tp> struct std::hash' in different namespace [-fpermissive]
 template <> struct std::hash<AFontSize> final
                                         ^~~~~
In file included from /usr/include/c++/6/bits/basic_string.h:5643:0,
                 from /usr/include/c++/6/string:52,
                 from /usr/local/include/wx-3.1/wx/stringimpl.h:66,
                 from /usr/local/include/wx-3.1/wx/unichar.h:15,
                 from /usr/local/include/wx-3.1/wx/strvararg.h:19,
                 from /usr/local/include/wx-3.1/wx/string.h:37,
                 from /usr/local/include/wx-3.1/wx/log.h:43,
                 from /wxmaxima/src/CellPtr.h:36,
                 from /wxmaxima/src/Cell.h:33,
                 from /wxmaxima/src/AbsCell.h:33,
                 from /wxmaxima/src/AbsCell.cpp:31:
````
I'm afraid I need help understanding that error message...

**Comment by gunterkoenigsmann** [comment] 2020-08-29 18:57
Probably resolved with 096cc442a5f2799d95c0a00146d768d8a0881a30.

**Comment by gunterkoenigsmann** [comment] 2020-08-30 20:51
Seems like the problem is worse than I thought: Forwarding from the maxima-discuss mailing list:
````
I added the flag -fpermissive which makes that particular error into a warning, but then I ran into this one:

/wxmaxima/src/cells/CellPtr.h:127:20: error: enclosing class of constexpr non-static member function 'void Observed::ControlBlock::reset()' is not a literal type
     constexpr void reset() noexcept { m_object = nullptr; }
                    ^~~~~
/wxmaxima/src/cells/CellPtr.h:88:9: note: 'Observed::ControlBlock' is not literal because:
   class ControlBlock final
         ^~~~~~~~~~~~
/wxmaxima/src/cells/CellPtr.h:88:9: note:   'Observed::ControlBlock' has a non-trivial destructor
/wxmaxima/src/cells/CellPtr.h:128:32: error: enclosing class of constexpr non-static member function 'Observed* Observed::ControlBlock::Get() const' is not a literal type
     constexpr inline Observed *Get() const noexcept { return m_object; }
                                ^~~
In file included from /wxmaxima/src/cells/Cell.h:33:0,
                 from /wxmaxima/src/cells/EditorCell.h:27,
                 from /wxmaxima/src/AutocompletePopup.h:42,
                 from /wxmaxima/src/AutocompletePopup.cpp:30:

````

**Comment by gunterkoenigsmann** [comment] 2020-09-01 06:15
@KubaO : On https://sourceforge.net/projects/maxima/lists/maxima-discuss there currently is a discussion why we by using c++11 dropped support for popular linux distributions like RedHat, CentOs and debian-oldstable.

My hope is now that they ship several compilers of which one supports the parts of c++11 we need.

I was completely surprised by that discussion since if the current maxima version crashes on startup on Ubuntu LTS, if it cannot load the `draw()` package on Debian-stable and Ubuntu LTS or if its testsuite only passes on compiler newer than the compilers debian-testing ships with they tell not to have enough manpower to care about that setups.

**Comment by KubaO** [comment] 2020-09-01 08:41
RHEL and CentOS build wxMaxima no problem as long as we’re talking about the current version (IIRC). Old ones probably don’t but then it’s not a problem as we should be building with a recent clang on anything that came out of RedHat anyway, since their stock C++ compilers have a long history of being crap. I’ll never forget the gcc “2.95” snafu they once caused. Nothing got much better since then. Even Microsoft doesn’t behave that way anymore.

But even RHEL 7 supported C++11 IIRC. With wxMaxima it’s more about C++14 support - already a 6-year-old standard that was fully supported by gcc in 2013 IIRC.

As for those compilation failures: they mostly have simple solutions and are not a big deal. Takes longer to complain about them than to fix the stuff. I can’t fix what I can’t locally test so if we are supposed to support some CentOS then we must do it in the CI, otherwise it’s not going to happen period. I basically don’t care about what goes on outside of platforms that get built on CI. Anyone can add CI support for their pet platform and I’ll gladly get the code to compile and pass tests and hopefully be usable by normal desktop users on such platform. But the complaints are misplaced: we accept contributions and to me “we care about a platform” is empty words without a pull request to at least get the platform set up in the CI so that a build attempt is made and fails. I understand that running CentOS builds in Travis is “interesting” and don’t care enough to mess with it. Maybe AppVeyor makes it easier? I don’t know. 

Needless to say, I’m not going to turn back from C++14 requirement. Longer term, wxMaxima will have requirements similar to those of Qt 6, because even if we don’t use Qt yet, we may in the future, or at least we may use some of the backend technologies that require modern compilers anyway. And if the community at large pushes back, they are free to do the maintenance on the old code base themselves, and enjoy the top-notch performance and memory use (lol) - that’s the beauty of open source. I basically do this stuff because it’s enjoyable, and if the community dislikes it - I’ll maintain my own fork and push it forward just as hard, whereas the original wxMaxima will become irrelevant in a matter of a year or so - or not. Again, I really, completely, seriously do not care and won’t even get upset. I’m not doing this stuff for anyone but myself, and forking is a trivial thing. Anyone can do it.

I have also explored machine-translating large portions of maxima itself into C++ (it’s been a decade of trying now, with slow but steady progress), and I think that it’s silly that maxima is still written in lisp. It loses a lot on maintainability and performance. Eventually (a couple of years) I’ll have a usable machine translation of maxima to C++ and then it’ll become an integral part of wxMaxima - again, I have 0 worries about anyone accepting it - I’ll do it because I want to, and because I believe in the technical merits of doing so, in maintainability, performance and feature set benefits it will provide. I want to make the legacy stuff irrelevant by sheer technical domination, and then it’s up to the users to stay with the old cruft or move on to the shiny, performant and featureful new stuff. 

But that’s all looking very far ahead - there’s man-years of work still. For now I need the hs(19) test to work on a machine with 2 gigs of RAM and respond instantly once maxima is finished sending xml. And I know that it’s feasible and I know how to do it so that’s what I’m doing. It will also cause major improvements in maintainability since all of the original “do we recalc now?” logic will be gone, and the behavior will become identical across platforms. But the recalc improvements and the cell slimming are all dependent on cell context, and introducing the context in small chunks is an endeavor of its own - I wouldn’t know how to do it if it wasn’t tried extensively first. I’m now prototyping just how to split that functionality: how to make an existing prototype integrable into the live code base (with the principle being that it all basically keeps stuff working and usable for monthly releases). It’s basically a prototype of a prototyping process now. Sounds silly but it’s essential.

There’s another crash caused by a regression that I’ll fix tomorrow, and hopefully that will cover what I recently broke :)

- Kuba

**Comment by gunterkoenigsmann** [comment] 2020-09-01 10:30
On Ubuntu traditionally all that is compiled using QT crashes immediately so I normally don't have QT installed on my machine. My guess is that they disagree with QT's more rolling-release approach.

---

About CentOs: Our docker-wxmaxima project could probably be changed to use a base image from that distri... ...and as far as I have understood currently it doesn't compile, anyway...

**Comment by gunterkoenigsmann** [comment] 2020-09-01 18:05
...on the plus side: https://github.com/wxMaxima-developers/docker-wxmaxima should be a working test vehicle.

**Comment by KubaO** [comment] 2020-09-04 18:22
The `enclosing class of constexpr non-static member function 'void Observed::ControlBlock::reset()' is not a literal type` bug was fixed in gcc 7.2, in 2017. If the docker container is using an older one, then sure, it won't build :(

**Comment by KubaO** [comment] 2020-09-13 05:31
> On Ubuntu traditionally all that is compiled using QT crashes immediately so I normally don't have QT installed on my machine. My guess is that they disagree with QT's more rolling-release approach.

I have had 0 trouble using Qt Creator on Ubuntu to work on wxMaxima (that's what I use on any other platform as well - on Windows and on Mac OS), and the vast majority of the [hundreds of mostly-Qt example projects I wrote for stackoverflow][1] runs without issues as long as it compiles. I have only done statistical sampling since I test those manually, but nothing really crashes :)

[1]: https://github.com/KubaO/stackoverflown/tree/master/questions

**Comment by KubaO** [comment] 2020-09-13 05:40
I've made a decision: I'm not touching that docker image. Please don't mention it again to me. I'm a human being, not a CI system. If it's not in a problem I can see in CI, then I'm positively, absolutely not interested since I have 0 time to mess about with oddball builds. If it builds in CI, then for me it builds, period. I'm not supporting any non-CI builds - it's about the worst possible use of my limited time I can devote to this project.

**Comment by lokedhs** [comment] 2020-09-13 06:13
The docker image isn't something you're supposed to run. Docker is merely
used to build the Appimage. The repository name is probably not very good,
since if you're not actually working on the wxMaxima project you should
never have to deal with Docker.

**Comment by KubaO** [comment] 2020-09-13 19:04
Oh I know all that - it doesn’t make much difference. Docker is not normally something that you’d look at, and here it’d be definitely used to watch the compiler errors pass by. Not my idea of fun at all. I have the CI integrated with the IDE so error messages from CI show up in the IDE as if I did a local build etc, can switch between error sets from multiple builds automatically just based on what git commit I have checked out - it pulls the relevant messages straight from the CI, and so on. This saves heaps of time. I have zero time to get some Docker image added to this mix. Sorry. And I have no way of running the result without moving files by hand etc (whereas on a VM it’s trivial). So - too much overhead. Way too much. I iterate sometimes a few dozen builds an hour. Every second counts. No joke. 

> 13 sep. 2020 kl. 2:13 fm skrev Elias Mårtenson <notifications@github.com>:
> 
> ﻿
> The docker image isn't something you're supposed to run. Docker is merely
> used to build the Appimage. The repository name is probably not very good,
> since if you're not actually working on the wxMaxima project you should
> never have to deal with Docker.
>

**Comment by KubaO** [comment] 2020-11-28 16:25
This error will be probably resolved as soon as #1412 is fixed. The issue is with subtle pedantism of g++ 5, and it's a fairly low hanging fruit. It'd be worth figuring out how to install this old gcc on Debian and add a build using that compiler - since it seems to be a fairly widespread version, unfortunately.

**Comment by KubaO** [comment] 2020-11-28 16:29
Good news: Debian has a g++-5 package. I'll add that as a compiler variant we build with and that should ensure this won't get broken again.

**Comment by KubaO** [comment] 2020-11-28 19:34
I believe that fixing #1412 has also fixed this. Please reopen if there are other problems.

**Closed by KubaO** 2020-11-28 19:34 UTC
