### ISSUE TITLE
wxmaxima on OSX (with homebrew)

### ISSUE THREAD

**Issue by neuwirthe** [wxMaxima-developers/wxmaxima#603] opened 2015-10-29 06:34 UTC
I installed wxmaxima 15.08.2 through homebrew on my Max with OSX 10.11.1 and there are issues with output with exponents. The attached screenshot shows the problem.
In plain maxima, everything is OK.

![screenshot_26](https://cloud.githubusercontent.com/assets/157619/10811705/17b9be38-7e0f-11e5-83f2-5a87a123beeb.png)

**Comment by neuwirthe** [comment] 2015-11-25 10:57
I found the reason for the issue. With
set_display('xml') 
the output is incorrect. With 
set_display('ascii')
things work.

**Comment by gunterkoenigsmann** [comment] 2015-11-27 11:41
The missing characters look to me like wxMaxima is trying to use a font that isn't installed or that doesn't provide the characters that are needed to display the output. Don't have a mac to test on, unfortunately.

Kind regards,

      Gunter.

**Comment by puiseux** [comment] 2016-01-11 05:19
Same problem for me. In wxmaxima/preferences, I hit "use jsfonts", (this family of font is present on my mac).
But output (with set_display('xml')) is still incomplete as shown here...
To be complete, I have to say this problem has always been the same with wxmaxime, since I use macosx (i.e. since more than 5 years). 
I never succeed in having nice output as expected. Despite a lot of research, I never found the reason.
Thanks for answer

**Comment by gunterkoenigsmann** [comment] 2016-01-11 05:44
If you uncheck "use jsfonts" and change the maths font - is the output still incomplete then? The maths are printed in the same way the labels and the inputs are, only with a different font (if a different font is selected) and 
![untitled](https://cloud.githubusercontent.com/assets/5041537/12227559/a95d4d1a-b82e-11e5-87d1-b24caea055d6.jpg)
there *has* to be a reason...

**Comment by puiseux** [comment] 2016-01-11 05:53
I cannot change font.
When I click on the button "choose font", wxmaxima shutdown.

**Comment by andrejv** [comment] 2016-01-11 09:44
@puiseux The issue with the font dialog is a bug in wxWidgets. I think that the homebrew version includes a patch, so if you install wxmaxima from homebrew, you should be able to change the font.

The configuration for wxmaxima is in ~/Library/Preferences/wxMaxima preferences. Try deleting this file and start wxmaxima again (make a backup before deleting).

**Comment by puiseux** [comment] 2016-01-16 10:23
Yes, it works. Thanks

**Comment by KubaO** [comment] 2020-07-10 20:12
Closing, since the reporter confirmed that it works.

**Closed by KubaO** 2020-07-10 20:12 UTC
