### ISSUE TITLE
wxMaxima is Crashing after few minutes of use

### ISSUE THREAD

**Issue by Dawncrypto** [wxMaxima-developers/wxmaxima#1204] opened 2020-02-01 02:09 UTC
Maxima software is abruptly crashing after every 3-4 minutes of use, in between the work.

**Comment by gunterkoenigsmann** [comment] 2020-02-01 06:50
What version of wxMaxima are you running? On which kind of system? And does the program give any error dialogue/ any hint of why it is crashing?

**Comment by gunterkoenigsmann** [comment] 2020-02-01 07:16
In most cases crashes are easily resolved once I find a way to reproduce them on my own computer.

**Comment by richardgobeli** [comment] 2020-03-03 22:55
I had it happen yesterday a few times.  it was inactive at the time.
The build info does not look formated anymore.
It also no longer allows me to copy it.
![image](https://user-images.githubusercontent.com/31253976/75827503-7857e280-5d6f-11ea-8a5c-ebb108735fa8.png)
So here is the bug report text.
My wxMaxima just crashed while writing this text.
(%i2)	wxbug_report()$
wxMaxima is a graphical front end for Maxima, which does the mathematics in the background.

If you encounter a mathematical problem, it is probably a Maxima bug und should be submitted there.

The Maxima bug database is available at

    https://sourceforge.net/p/maxima/bugs

Submit bug reports by following the 'Create Ticket' link on that page.

To report a Maxima bug, you must have a Sourceforge account.

A problem in the graphical user interface is probably a wxMaxima bug.

The wxMaxima bug database is available at

    https://github.com/wxMaxima-developers/wxmaxima/issues

Submit bug reports by following the 'New issue' link on that page.

Please check before submitting, if your bug was already reported.

Please include the following information with your bug report:

-------------------------------------------------------------

wxMaxima version: 20.02.4_MSW_OpenMP201511+Locks

using wxWidgets version: wxWidgets 3.1.3

Maxima version: branch_5_43_base_374_gad9070256

Maxima build date: 2020-02-28 00:03:22

Host type: x86_64-w64-mingw32

System type: Win32 6.2.9200 X86-64

Lisp implementation type: SBCL

Lisp implementation version: 2.0.0

wxMaxima's idea of the directory layout is:

User configuration dir: C:\Users\100024837/maxima/

Help dir: C:\maxima-current\share/doc/wxmaxima

-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment] 2020-03-04 05:36
Hmmm... ...look like a fairly new wxMaxima. What are the symptoms of the crash? Does the window just disappear or does it provide any message telling it has crashed? If something happens after a few minutes of inactivity that looks like some bug in the autosave code. But that part of the program should always output debug messages if something is wrong.

**Comment by richardgobeli** [comment] 2020-03-04 08:00
Yes the window just disappears. No messages that can be seen.

**Comment by gunterkoenigsmann** [comment] 2020-03-08 07:21
Yesterday I've changed a few things with the saving code. I cannot guarantee that that has helped. But with a bit of luck it might have.

**Comment by Turik-Jr** [comment] 2020-04-06 16:33
Execute like administrator.

**Comment by KubaO** [comment] 2020-06-02 16:37
> Try to execute like administrator.

Bad idea. Don't do that. wxMaxima does not need administrator permissions. It's dangerous to run it with admin permissions - it's dangerous to run most software that way, in fact.

**Comment by KubaO** [comment] 2020-06-10 04:43
Due to the extent of changes done to the code between then and now, and the scant information provided, I’m closing this issue. If the problem persists for you with the current version, please create a new issue with more detail.

**Closed by KubaO** 2020-06-10 04:43 UTC
