### ISSUE TITLE
demo functions have no newline for input.

### ISSUE THREAD

**Issue by richardgobeli** [wxMaxima-developers/wxmaxima#1365] opened 2020-08-01 19:29 UTC
item 1:
demo(tensor) does not get a new line for input. The display is very different.  It always stops at the end of the output line. The cursor is at the right of the semicolon. This has start in the last week, I believe.  There is no spacing anymore.  The $ does not show on the demo input line.
![image](https://user-images.githubusercontent.com/31253976/89108849-8898ea00-d401-11ea-9215-0d00b6c3c35d.png)

item 2:
The last input character is always still in the input buffer.
I have not input anything from the last enter used to end the last demo statement.  The 1; is still there.   If I press shift enter again, it will do the 1. basics function again.  This has been doing this for some months.  I need to back space to change the enter.  This is not correct.
![image](https://user-images.githubusercontent.com/31253976/89108882-01984180-d402-11ea-99eb-1400709ddd3a.png)

![image](https://user-images.githubusercontent.com/31253976/89109047-5daf9580-d403-11ea-92bd-487c9bfbb275.png)

**Comment by gunterkoenigsmann** [comment] 2020-08-02 07:37
I never thought I would ever actually say this. But this is not a bug, but a feature - and actually one that was difficult to write: Since maxima's assume() command doesn't really work, maxima therefore in every run asks the same questions - and sometimes the answers to the questions are important (they aren't in the most common cases, though) I've made wxMaxima remember the last answer to questions. In practice this serves two purposes:

- It makes wxMaxima remember answers the user wants to fill in in a certain place and
- if the user wants to try all answers it tells where this attempt was left of.

I would never have thought that this feature would end up being controversial. As it did I have additionally added a configuration dialogue checkbox that tells wxMaxima not to fill the answer to known questions. But there are so many such options that I guess that this one is too hard to find - and I guess I would need a native english speaker who revises the wording I used there.

**Comment by richardgobeli** [comment] 2020-08-02 15:31
Thanks, I did not know about this and it has been annoying me for some time.  Running demos you usually don't want to repeat any of the answers.  So I am glad to be able to turn this off and on when needed.
The output stills needs to be restored.  I see that is why this was left open.
Thanks.

**Comment by richardgobeli** [comment] 2020-08-02 16:33
Here is another spot where the input and output is not right.
I was trying to enter a diagonal metric and WxMaxima seems not to prompt for input.  This may be a problem with Maxima, because this is normally a dialog box input and here it is a line input. 
![image](https://user-images.githubusercontent.com/31253976/89127540-cd7d5900-d4b3-11ea-9907-c8bbdf4170f1.png)
![image](https://user-images.githubusercontent.com/31253976/89127573-087f8c80-d4b4-11ea-9051-c13cc6b5ffd3.png)

**Comment by gunterkoenigsmann** [comment] 2020-08-06 06:00
That's what testers are important for: Adding items to the worksheet now uses as fool-proof memory management as c++11 will provides us with - but in one case we completely forgot to do so. Thanks a lot!

**Comment by richardgobeli** [comment] 2020-08-07 23:26
At least I can see the prompt with a magnifying glass.
![image](https://user-images.githubusercontent.com/31253976/89695912-5f81c900-d8db-11ea-86db-0ad4fa80e335.png)
The Demo is also the same input is on the end of the output line.
![image](https://user-images.githubusercontent.com/31253976/89695973-83450f00-d8db-11ea-9865-5f6bbadcd3c2.png)

**Comment by gunterkoenigsmann** [comment] 2020-08-12 21:11
In tomorrow's build the newlines should be present.

But for the test size I have no idea what to do: Maxima clearly states it wants a label - and labels are scaled to fit into the width the config dialogue reserves for labels.

**Comment by richardgobeli** [comment] 2020-08-13 09:58
This is better.
![image](https://user-images.githubusercontent.com/31253976/90120855-daeeda80-dd20-11ea-832c-0b279d1b8da5.png)
![image](https://user-images.githubusercontent.com/31253976/90120917-efcb6e00-dd20-11ea-9ce5-3e6f9048dc13.png)

**Comment by gunterkoenigsmann** [comment] 2020-08-13 10:20
@KubaO 's improvements have made resolving many bugs way easier.

**Comment by richardgobeli** [comment] 2023-06-27 03:10
Did this type of error come back?
The end of the output has a red underscore mark and the semicolon looks like is tabbed over a few spaces.
I could not find your setting that auto repeats answers in the configuration to set if my setting has changed.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/c37f59a5-360d-4bdf-b2ba-3fb45e98a440)
This is the version I am running.

![image](https://github.com/wxMaxima-developers/wxmaxima/assets/31253976/cef4c58f-c4de-4de7-81ee-9734132cf8db)

**Closed** 2024-01-01 23:28 UTC
Labels: bug, nightly
