### ISSUE TITLE
Style settings

### ISSUE THREAD

**Issue by ljselmaier** [wxMaxima-developers/wxmaxima#1263] opened 2020-05-02 17:10 UTC
(%i1)	build_info();
(%o1)	build_info(version="branch_5_43_base_495_g6c33908e1",
timestamp="2020-05-01 23:10:06",host="i686-w64-mingw32",
lisp_name="SBCL",lisp_version="1.4.14",maxima_userdir=
"C:/Users/LJSelmaier/maxima",maxima_tempdir=
"C:/Users/LJSelmaier/AppData/Local/Temp",maxima_objdir=
"C:/Users/LJSelmaier/maxima/binary/branch_5_43_base_495_g6c33908e1/sbcl/1_4_14"
,maxima_frontend="wxMaxima",maxima_frontend_version=
"20.04.0-DevelopmentSnapshot_MSW_OpenMP201511+Locks")

![wxMaxima_Error](https://user-images.githubusercontent.com/59099908/80870684-6aa7d600-8ca8-11ea-9ed6-957cd2b45e24.jpg)

The display are not right.
There is no effect, when I change the settings.

**Comment by Kaiser1401** [comment] 2020-05-06 09:45
seems to be related to  #1103

**Comment by ljselmaier** [comment] 2020-05-09 14:46
It is not the same.
Not change language, change **font styles**.

**Comment by ljselmaier** [comment] 2020-05-09 15:02
It is not the same.
Not change language, change font styles.

**Comment by Kaiser1401** [comment] 2020-05-09 18:51
I'm expecting it to be the same problem (with different symptoms). Or does changing languages work in your case?

**Comment by gunterkoenigsmann** [comment] 2020-05-09 19:31
Is the language selection still broken in the nightly builds? I thought I had finally found the problem: wxMaxima stores the number of the language - in Windows in the registry, on the rest of the operating systems in a config file - and on opening the program the number is restored correctly - only that I manged to introduce more than one bug in the code that dealt with the number.

The problem with styles is that they provide a lot of options - and it is hard to test all combinations. But there is good news here: Kuba is currently reworking the code that deals with fonts and styles in a way that drastically improves the performance and normally his code removes many bugs and possibilities to introduce bugs so I expect this aspect of wxMaxima to improve in the next few weeks. I don't dare to change too much of this code, currently, as this normally causes additional work for him; If the performance improvements don't fix all problems with restoring and saving styles I am afraid that we'll have to find each bit of information that isn't correctly restored one by one and fix it. But with a little help from you as testers that will be no big problem, neither.

**Comment by KubaO** [comment] 2020-05-19 06:12
It is true that a lot of the style handling code will get dumped. The first set of changes I'm very close to finishing gets rid of the remaining font-related slowdowns, and it makes the style code more robust. That includes getting rid of repeated font selection code, and provides one central place where you can debug the transition between a style and its font (namely: `Style::GetFont` and `Style::GetFontAt`).

**Comment by KubaO** [comment] 2020-06-01 06:53
This is related to broken font styling, where it selects invalid defaults and overrides existing settings. This shows up on Windows, but is a sign of a deeper problem. These issues are all related, but I'll leave them open without flagging as duplicates, until the problem is fixed.

**Comment by KubaO** [comment] 2020-07-09 05:30
This is fixed in master.

**Closed by KubaO** 2020-07-09 05:30 UTC
Labels: bug, confirmed
