### ISSUE TITLE
Error after plot2d XML parsing error

### ISSUE THREAD

**Issue by barddoo** [wxMaxima-developers/wxmaxima#1150] opened 2019-08-18 03:18 UTC
I made a simple function using plot2d and those messages came up, but everything is still running, it not even broke or closed. 
OS: Ubuntu 19.04
version: 19.07.0
![Screenshot from 2019-08-18 00-08-09](https://user-images.githubusercontent.com/45905884/63219685-93556300-c14d-11e9-8c44-7c3ebf440509.png)

**Comment by gunterkoenigsmann** [comment] 2019-08-30 19:44
Hmmm... ...cannot reproduce this still. And I seem to have written but not send a response to this ticket.
The GTK message seems to come from gnuplot. And it seems to contain non-unicode chars - which I would expect to happen only on MS Windows, not on Linux or on a Mac Os. Could you send me the whole red error message - and what happens if you send the following commands to maxima?

     load("operatingsystem");
     getenv("LANG");

**Comment by KubaO** [comment] 2020-07-10 16:50
@barddoo I'm closing this since I believe that it is fixed now. Please reopen this issue if the problem is present in the master branch or the nightly build.

**Closed by KubaO** 2020-07-10 16:50 UTC
