### ISSUE TITLE
Integration display: no dx in xml

### ISSUE THREAD

**Issue by JustTheEngineer** [wxMaxima-developers/wxmaxima#1332] opened 2020-07-10 16:20 UTC
When displaying an integral, the "dx" is missing when set_display('xml).
If you copy it, you get: integrate(x,,0,1), which is clearly missing an x in the second place (the original is 'integrate(x,x,0,1);).
When you set the display to ascii, you do get the "dx". 

See picture. 
![Clipboard01](https://user-images.githubusercontent.com/8266088/87176051-d0809180-c2d9-11ea-8f93-70791d0d1969.png)

It's annoying to make courses, 

Thanks for looking into it. 

Rudy

wxMaxima version: 20.06.6_MSW_OpenMP201511+Locks
using wxWidgets version: wxWidgets 3.1.3
Maxima version: 5.44.0
Maxima build date: 2020-06-08 22:46:53
Host type: x86_64-w64-mingw32
System type: Win32 6.2.9200 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 2.0.0
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\rudy/maxima/
Help dir: F:\Extra\maxima-5.44.0\share/doc/wxmaxima

**Comment by KubaO** [comment] 2020-07-10 18:33
This is a duplicate of #1307. Try the nightly build where it's fixed.

**Closed by KubaO** 2020-07-10 18:33 UTC
Labels: bug, release-critical-bug
