### ISSUE TITLE
Spacing between negative sign and fraction is too small.

### ISSUE THREAD

**Issue by jabowery** [wxMaxima-developers/wxmaxima#563] opened 2015-09-12 17:14 UTC
In the attached screen shot, note that the second component of both vectors have identical formulas when the expression is not surrounded by "float()".  When it is surrounded by "float()" however, it correctly shows that one is the negation of the other.

![screen shot 2015-09-12 at 12 10 56 pm](https://cloud.githubusercontent.com/assets/57646/9832648/8985a690-5947-11e5-8ae1-07b70cfe4d78.png)

**Comment by gunterkoenigsmann** [comment] 2015-09-12 17:23
Dear James,

This looks strange.

Does it still happen after typing:

     display2d:false;

And the second question: Would it be possible for you to provide us (or 
the maxima project if the problem happens to be on their side) with a 
minimal example of an equation that allows to debug where the minus 
gets lost?

Thanks a lot,
and kind regards,

   Gunter.

**Comment by KubaO** [comment] 2020-07-10 19:01
If one looks carefully at the screenshot (at full size, not the scaled down preview in the issue above - click on it!), it is clear that there is a small space between the minus and the first result. Thus it's not true that both vectors have identical formulas. But it is a rendering spacing bug between `-` and a fraction. This may possibly be because the `-` sign somehow ended up italicized.

Alas, it's not possible to reproduce this anymore, thus I'm closing this one.

**Closed by KubaO** 2020-07-10 19:01 UTC

**Comment by KubaO** [comment] 2020-07-10 19:45
Duplicate of #640.
