### ISSUE TITLE
wxMaxima parses the Maxima manual every time, 100% CPU

### ISSUE THREAD

**Issue by TomasRiker** [wxMaxima-developers/wxmaxima#1736] opened 2022-12-19 15:29 UTC
Every time I open wxMaxima (latest nightly build from Wolfgang Dautermann's website, 2022-12-19), it spends about 40 seconds (on my slightly outdated machine) parsing the Maxima manual. While doing so, it utilizes 100% of one CPU core. I think it should be doing that only once and save the parsing result to the disk.

**Comment by gunterkoenigsmann** [comment] 2022-12-19 18:36
In theory the messages in the debug sidebar should contain enough information to tell us what went wrong with restoring the cache. If it doesn't I'll add another message for tomorrow's Nightly Build.

**Comment by gunterkoenigsmann** [comment] 2022-12-19 18:38
That means: On 2022-12-19 until today maxima had a bug that hindered wxMaxima from reading many of its variables. With much luck tomorrow's nightly build will resolve that issue without us having to do anything.

**Comment by TomasRiker** [comment] 2022-12-20 02:58
This is the content of the debug sidebar:

> 03:56:35: wxMaxima version 22.11.1
> 03:56:35: Running on MS Windows using DirectDraw
> 03:56:35: OS: Windows 10 (build 19045), 64-bit edition Version 10.0
> 03:56:35: wxWidgets 3.2.1
> 03:56:35: Translations are read from C:\Portable\wxMaxima\share/locale.
> 03:56:35: Reading the config from the default location.
> 03:56:35: A text control got the mouse focus
> 03:56:36: Gnuplot found at: C:\Portable\wxMaxima\bin\..\gnuplot\bin\gnuplot.exe
> 03:56:36: LANG=en_GB.UTF-8
> 03:56:36: Worksheet got the mouse focus
> 03:56:36: Trying to start the socket a maxima on the local machine can connect to on port 4021
> 03:56:36: Server started
> 03:56:36: Running maxima as: "C:\Portable\wxMaxima\bin\maxima.bat"  -s 4021 
> 03:56:36: Welcome to wxMaxima
> 03:56:36: Sending maxima the info how to express 2d maths as XML
> 03:56:36: Reading the Lisp part of wxMaxima from the included header file.
> 03:56:36: Updating maxima's configuration
> 03:56:36: Setting prompt and help format
> 03:56:36: Sending configuration data to maxima.
> 03:56:36: Received maxima's first prompt: pid=3120â†²Maxima branch_5_46_base_791_ge0b6d8d3c_dirty https://maxima.sourceforge.ioâ†²using Lisp SBCL 2.2.11â†²Distributed under the GNU Public License. See the file COPYING.â†²Dedicated to the memory of William Schelter.â†²The function bug_report() provides bug reporting information.â†²(451) <suppres
> 03:56:36: Maxima's PID is 3120
> 03:56:36: Maxima has authenticated!
> 03:56:36: Maxima is ready for input.
> 03:56:37: Scheduling a background task that compiles a new list of autocompletable maxima commands.
> 03:56:37: Gnuplot found at: C:\Portable\wxMaxima\bin\..\gnuplot\bin\gnuplot.exe
> 03:56:37: Querying gnuplot which graphics drivers it supports.
> 03:56:37: Maxima version: branch_5_46_base_791_ge0b6d8d3c_dirty
> 03:56:37: Maxima user configuration lies in directory C:/Users/David/maxima
> 03:56:37: Maxima uses temp directory C:/Users/David/AppData/Local/Temp
> 03:56:37: Maxima's share files lie in directory C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/share
> 03:56:37: Maxima's manual lies in directory C:/Portable/wxMaxima/share/info
> 03:56:37: Maxima's HTML manuals are in directory C:\Portable\wxMaxima\share\maxima\branch_5_46_base_791_ge0b6d8d3c_dirty\doc
> 03:56:37: Found the maxima HTML manual in the folder C:\Portable\wxMaxima\share\maxima\branch_5_46_base_791_ge0b6d8d3c_dirty\doc\html.
> 03:56:37: No file with the subjects the manual contained in the last wxMaxima run.
> 03:56:37: Maxima architecture: x86_64-w64-mingw32
> 03:56:37: Maxima was compiled using SBCL
> 03:56:37: Lisp version: 2.2.11
> 03:56:37: Maxima sends a new set of auto-completable symbols.
> 03:56:37: Maxima sends a new set of auto-completable symbols.
> 03:56:37: Autocompletion: Scanning C:\Portable\wxMaxima\share\maxima\branch_5_46_base_791_ge0b6d8d3c_dirty\share\ recursively for loadable lisp files.
> 03:56:37: Trying to load a list of autocompletable symbols from file C:\Users\David\maxima\wxmaxima.ac
> 03:56:37: Autocompletion: Scanning C:\Users\David\maxima\ for loadable lisp files.
> 03:56:37: Found 1256 loadable files.
> 03:56:37: Autocompletion: Scanning C:\Portable\wxMaxima\share\maxima\branch_5_46_base_791_ge0b6d8d3c_dirty\ for loadable demo files.
> 03:56:37: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/doc/html/index.html for anchors
> 03:56:37: Found 112 demo files.
> 03:56:38: Terminals supported by gnuplot: caca cairolatex canvas cgm context domterm dumb dxf eepic emf emtex epscairo epslatex fig gif hpgl jpeg latex lua mf mp pcl5 pdfcairo png pngcairo postscript pslatex pstex pstricks qms qt sixelgd svg texdraw tgif tikz tkcanvas tpic unknown windows wxt
> 03:56:38: Using gnuplot's pngcairo driver for embedded plots
> 03:56:38: Found 0 anchors, 0 anchors total.
> 03:56:38: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/doc/html/intromax.html for anchors
> 03:56:39: Found 0 anchors, 0 anchors total.
> 03:56:39: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/doc/html/maxima_singlepage.html for anchors
> 03:57:10: Found 0 anchors, 0 anchors total.
> 03:57:10: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/share/algebra/solver/solver1-en.html for anchors
> 03:57:11: Found 0 anchors, 0 anchors total.
> 03:57:11: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/share/contrib/Eulix/Eulix.html for anchors
> 03:57:11: Found 4 anchors, 4 anchors total.
> 03:57:11: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/share/contrib/symplectic_ode/symplectic_ode.html for anchors
> 03:57:11: Found 0 anchors, 4 anchors total.
> 03:57:11: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/share/physics/dimension.html for anchors
> 03:57:11: Found 0 anchors, 4 anchors total.
> 03:57:11: Scanning help file C:/Portable/wxMaxima/share/maxima/branch_5_46_base_791_ge0b6d8d3c_dirty/share/pytranslate/maxima-to-ir.html for anchors
> 03:57:11: Found 6 anchors, 10 anchors total.
> 03:57:11: Using the built-in list of manual anchors.
> 03:57:11: Maxima version: branch_5_46_base_791_ge0b6d8d3c_dirty, Anchors cache version

**Comment by TomasRiker** [comment] 2022-12-20 23:53
The same still happens with today's nighly build.

**Comment by gunterkoenigsmann** [comment] 2022-12-22 06:13
wxMaxima is told that maxima's HTML documentation can be found in the directory `C:\Portable\wxMaxima\share\maxima\branch_5_46_base_791_ge0b6d8d3c_dirty\doc\html` and then finds only two files there that both don't contain any jump marks ("anchors") in a format it recognizes. Could you send me the _singlepage file (either renamed to .txt here or if that doesn't work to wxMaxima at peterpall.de per mail) - and the manual should be about a hundred HTML files. Can you tell me where to find them so I can teach wxMaxima that?

**Comment by TomasRiker** [comment] 2022-12-22 18:36
Here's the zipped file.
[maxima_singlepage.zip](https://github.com/wxMaxima-developers/wxmaxima/files/10289549/maxima_singlepage.zip)

I realize I didn't tell you that I don't use wxMaxima's installer (like many people, I always try to install software in a portable way without using any installers). I just open the .exe file with 7zip and extract everything. Is there a manual-related step that would have been done by the installer?

**Comment by richardgobeli** [comment] 2022-12-23 16:19
I use the normal windows installer and I get this debug message.  The cache version seems to be different.
No anchors were found.
![image](https://user-images.githubusercontent.com/31253976/209365903-26860971-08c2-4451-9ac9-bbd591e5369e.png)
This is from last night's build.
![image](https://user-images.githubusercontent.com/31253976/209366229-0dfdaec7-56fa-4962-aff3-b3ca15280df8.png)

**Comment by TomasRiker** [comment] 2022-12-27 00:51
Still the same behavior with the latest nightly build from Wolfgang Dautermann's website (December 27th, 00:40). The changelog of the wxMaxima version that's included contains the latest additions, so I assume that this build contains the commits that were supposed to fix this. Didn't work for me.

**Comment by gunterkoenigsmann** [comment] 2022-12-27 13:22
Thanks for testing this again! Finally found a way to reproduce this issue on my own computer. On the plus side autosave now is fast even if many animations are involved.

**Comment by gunterkoenigsmann** [comment] 2022-12-29 02:19
According to my virtual Windows PC that issue is resolved with yesterday's build.

**Closed by gunterkoenigsmann** 2022-12-29 02:19 UTC
